import React, { useState, useEffect, useCallback, useRef } from "react";
import { Link } from "react-router-dom";
import { Delete, Share2 } from "lucide-react";
import { shared, colors, usePageTitle, copyToClipboard } from "../theme";
import PageShell from "../components/PageShell";
import Leaderboard, { SaveScoreRow } from "../components/Leaderboard";

// The curated pool of common, everyday words the game picks its answer
// from — kept separate from the full dictionary below so answers stay
// fun and guessable rather than obscure dictionary entries. Sourced and
// hand-checked from Norsk ordbank – bokmål 2005 plus common inflected
// forms (definite/plural) not in the base lemma list.
const ANSWER_WORDS = [
  "STOLT", "VINDU", "HAGEN", "SKOLE", "TOGET", "HUSET", "BILEN", "FJORD",
  "FJELL", "TORSK", "KAFFE", "EGGET", "SUPPE", "KJØTT", "FISKE", "BADET",
  "TAKET", "DØREN", "HAGER", "AVISA", "BYGDA", "JENTA", "DAMEN", "BARNA",
  "FAREN", "MOREN", "BÅTEN", "FLYET", "VEIEN", "BROEN", "HAVET", "SJØEN",
  "ELVEN", "DALEN", "ØYENE", "SOLEN", "MÅNEN", "STORM", "SKYEN", "SNØEN",
  "FROST", "VARME", "LYSET", "MØRKE", "FARGE", "LITEN", "STORE", "VAKRE",
  "STYGG", "GLADE", "TRIST", "REDDE", "MODIG", "STERK", "SVAKE", "RASKE",
  "TREGE", "KLOKE", "VOKSE", "SPISE", "LESER", "LØPER", "HOPPE", "DANSE",
  "SYNGE", "SPILL", "LEKER", "BØKER", "KUNST", "MALER", "TEGNE", "KRONE",
  "VERDI", "KJØPE", "SELGE", "JOBBE", "LÆRER", "BOKEN", "PAPIR", "HVITT",
  "BRUNT", "GRØNT", "LILLA", "GRÅTT", "SVART", "KLART", "ENKEL", "FALSK",
  "SANNE", "NYTTE", "HJELP", "TRENE", "SYKLE", "KJØRE", "FLYGE", "SEILE",
  "TUREN", "FERIE", "REISE", "MOTOR", "BREMS", "GATER", "PLASS", "KVELD",
  "TØRST", "TRØTT", "GLEDE", "FRYKT", "HÅPET", "ANGST", "YDMYK",
  "ELGEN", "BJØRN", "REVEN", "ULVEN", "HJORT", "SVANE", "ØRNEN", "KRÅKE",
  "SNEGL", "HAREN", "GEITA", "SAUEN", "HANEN", "BIENE", "FLUEN",
  "ARMEN", "HODET", "HÅRET", "ØRENE", "NESEN", "MAGEN", "LEVER", "LUNGE",
  "HAKEN", "SMØRE", "SALTE", "EPLET", "PÆREN", "DRUER", "POTET", "LØKEN",
  "SALAT", "KAKAO", "KAKEN", "SMAKE", "STEKE", "KOKER", "BAKER", "SKJÆR",
  "SPEIL", "STIGE", "KOSTE", "SKAPE", "HYLLE", "LAMPE", "PUTER", "TEPPE",
  "VASKE", "RYDDE", "LÅSEN", "SLIPS", "BELTE", "LOMME", "KNAPP", "DRAKT",
  "KÅPEN", "STEIN", "LEIRE", "GRESS", "ROTEN", "GREIN", "ØRKEN", "BREEN",
  "LYNET", "TIMEN", "UKENE", "ÅRENE", "DAGEN", "FEMTI", "TUSEN", "SINNA",
  "SJALU", "ÆRLIG", "FRISK", "TENKE", "HUSKE", "SKRIK", "LATTE", "VELGE",
  "START", "SLUTT", "ENDRE", "PRØVE", "VINNE", "TAPER", "BYGGE", "SVARE",
  "LYTTE", "SANSE", "FØLER", "TENKT", "VISST", "HELLE", "TILBY", "FORBI",
  "INNOM",
];

// Full accepted-guess dictionary, sourced from Norsk ordbank – bokmål 2005
// (Språkrådet / University of Bergen, CC-BY 4.0), filtered to 5-letter
// words with a basic profanity filter applied. This is what validates
// whether a typed guess counts as a real word. 5,157 words.
const VALID_GUESSES = new Set([
  "ABAYA", "ABBED", "ABBOR", "ABORT", "ABROT", "ADEPT", "ADOBE", "ADVIS", "AEROB", "AFASI",
  "AFORI", "AFTEN", "AGAPE", "AGAVE", "AGENS", "AGENT", "AGERE", "AGNAT", "AGNOR", "AGONI",
  "AGORA", "AGRAR", "AGURK", "AIOLI", "AIVAR", "AKING", "AKKAR", "AKRYL", "AKSEL", "AKSJE",
  "AKSLE", "AKSON", "AKTER", "AKTET", "AKTIN", "AKTIV", "AKTOR", "AKTRE", "AKTØR", "AKUTT",
  "ALALI", "ALANT", "ALARM", "ALBIN", "ALBUE", "ALBUM", "ALDER", "ALDRE", "ALDRI", "ALENE",
  "ALERT", "ALEUT", "ALGIN", "ALIAS", "ALIBI", "ALING", "ALKAN", "ALKEN", "ALKIS", "ALKYD",
  "ALKYL", "ALKYN", "ALLEL", "ALLER", "ALLYL", "ALPIN", "ALTAN", "ALTER", "ALTSÅ", "ALVED",
  "ALVOR", "AMBAR", "AMBRA", "AMCAR", "AMORF", "AMPEL", "AMPER", "AMØBE", "ANBUD", "ANDEL",
  "ANDRA", "ANDRE", "ANEMI", "ANGEL", "ANGER", "ANGLE", "ANGRE", "ANGST", "ANING", "ANION",
  "ANKEL", "ANKER", "ANKRE", "ANLØP", "ANNAL", "ANNEN", "ANODE", "ANROP", "ANSLÅ", "ANSTÅ",
  "AORTA", "APATI", "APERI", "APHEL", "APING", "APOGE", "APRIL", "APSIS", "AREAL", "ARENA",
  "ARGON", "ARGOT", "ARIER", "ARILD", "ARISK", "ARKIV", "ARMEN", "ARMOD", "AROMA", "ARRET",
  "ARRIG", "ARSEN", "ARTIG", "ARVES", "ASDIC", "ASETE", "ASIAT", "ASKET", "ASPIK", "ASTAT",
  "ASTMA", "ATLAS", "ATLET", "ATOLL", "ATONI", "ATOPI", "ATSJO", "ATTEN", "ATTER", "ATTOM",
  "ATTPÅ", "ATTRE", "ATTRÅ", "ATTÅT", "ATYPI", "AUGUR", "AUING", "AURET", "AURUM", "AUSTA",
  "AUTOR", "AVART", "AVBUD", "AVDAL", "AVDRA", "AVDØD", "AVENY", "AVERS", "AVGUD", "AVHØL",
  "AVHØR", "AVIND", "AVISA", "AVISE", "AVISO", "AVKLE", "AVKOK", "AVKOM", "AVLAT", "AVLER",
  "AVLYD", "AVLØP", "AVROP", "AVSIG", "AVSKY", "AVSLÅ", "AVSTÅ", "AVSUG", "AVSVI", "AVTAK",
  "AVUND", "AVVEG", "AVVEI", "AVVIK", "BABEL", "BABLE", "BACON", "BADER", "BADET", "BAGGE",
  "BAHAI", "BAJAS", "BAKER", "BAKKE", "BAKLI", "BAKOL", "BAKOM", "BAKPÅ", "BAKRE", "BAKSE",
  "BAKST", "BAKUT", "BALJE", "BALLE", "BALSA", "BAMSE", "BANAL", "BANAN", "BANDE", "BANDY",
  "BANGE", "BANJO", "BANKE", "BANKO", "BANNE", "BANTU", "BARDE", "BARKA", "BARKE", "BARNA",
  "BARON", "BARRE", "BARSK", "BASAL", "BASAR", "BASIS", "BASKE", "BASME", "BASSE", "BASSO",
  "BASTA", "BASTE", "BASUN", "BATAK", "BATCH", "BAUGE", "BAUSE", "BAUTA", "BAUTE", "BAYER",
  "BEBOP", "BEDRA", "BEDRE", "BEFAL", "BEFRI", "BEGER", "BEGGE", "BEGLO", "BEHAG", "BEHOV",
  "BEIGE", "BEILE", "BEINE", "BEING", "BEISE", "BEISK", "BEIST", "BEITE", "BEJAE", "BEKLE",
  "BELJE", "BELME", "BELTE", "BELØP", "BEMBA", "BENDE", "BENET", "BENKE", "BENZO", "BERET",
  "BERGE", "BERME", "BERTE", "BESLÅ", "BESNE", "BESTÅ", "BESYV", "BESØK", "BETEL", "BETLE",
  "BETRE", "BETRO", "BEVEN", "BEVER", "BEVIS", "BEVRE", "BEÆRE", "BIAVL", "BIBEL", "BIDIG",
  "BIDRA", "BIELV", "BIENE", "BIFAG", "BIFIL", "BIGAM", "BIING", "BIKKE", "BIKSE", "BIKTE",
  "BILAG", "BILDE", "BILEN", "BILIN", "BILKØ", "BILLE", "BILYD", "BIMBO", "BINDE", "BINGE",
  "BINGO", "BINNE", "BINOM", "BINÆR", "BISAK", "BISAM", "BISLE", "BISNE", "BISOL", "BISON",
  "BISTÅ", "BITEN", "BITTE", "BIVRE", "BJEFF", "BJERK", "BJØRK", "BJØRN", "BLAFF", "BLAKK",
  "BLANK", "BLANT", "BLASS", "BLAUT", "BLEIE", "BLEIG", "BLEIK", "BLEKE", "BLEKK", "BLEST",
  "BLIKK", "BLIND", "BLING", "BLINK", "BLITS", "BLITZ", "BLIVE", "BLOGG", "BLOKK", "BLOME",
  "BLOND", "BLOTE", "BLOTT", "BLUES", "BLUFF", "BLUND", "BLUNK", "BLUSE", "BLUSS", "BLYGD",
  "BLÅIS", "BLÅNE", "BLÅSE", "BLÅST", "BLÅTT", "BLÆRE", "BLØFF", "BLØTE", "BLØYT", "BOBBY",
  "BOBIL", "BOBIN", "BOBLE", "BOGEY", "BOGGI", "BOGNE", "BOHEM", "BOING", "BOJAR", "BOKEN",
  "BOKNE", "BOKSE", "BOKÅR", "BOLER", "BOLIG", "BOLKE", "BOLLE", "BOLNE", "BOLTE", "BOMBE",
  "BOMKØ", "BOMME", "BONDE", "BONGE", "BONGO", "BONUM", "BONUS", "BOOKE", "BOOTS", "BOPEL",
  "BORAT", "BORDE", "BORER", "BORGE", "BORRE", "BORSJ", "BORTE", "BORTI", "BOSON", "BOSSE",
  "BOTID", "BOTNE", "BOWLE", "BRAGD", "BRAKE", "BRAKK", "BRAND", "BRANN", "BRASE", "BRASK",
  "BRASS", "BRAST", "BRATT", "BRAUT", "BRAVO", "BREDD", "BREEN", "BREIE", "BREIS", "BREKE",
  "BREKK", "BREMS", "BRETT", "BRIFE", "BRIGG", "BRIKS", "BRINK", "BRISE", "BRISK", "BRIST",
  "BRITE", "BRODD", "BROEN", "BROKK", "BROTT", "BRUDD", "BRUKE", "BRUKT", "BRUNE", "BRUNT",
  "BRUSE", "BRUSK", "BRYDD", "BRYGG", "BRYNE", "BRYSK", "BRYST", "BRYTE", "BRÅKE", "BRÅNE",
  "BRÅTE", "BRØDE", "BRØLE", "BRØNN", "BRØST", "BRØYT", "BUBIL", "BUDEN", "BUDØL", "BUFAR",
  "BUFFE", "BUFFO", "BUFRE", "BUGNE", "BUING", "BUKKE", "BUKLE", "BUKSE", "BUKTE", "BULET",
  "BULKE", "BULLE", "BULNE", "BUMSE", "BUNAD", "BUNKE", "BUNNE", "BUNTE", "BUORM", "BURDE",
  "BURKA", "BUROT", "BUSKE", "BUSSE", "BUSTE", "BUTAN", "BUTID", "BUTTE", "BYBUD", "BYDAG",
  "BYDEL", "BYGDA", "BYGET", "BYGGE", "BYING", "BYKSE", "BYLIV", "BYLTE", "BYMUR", "BYMÅL",
  "BYNÆR", "BYRDE", "BYRÅD", "BYSSE", "BYSTE", "BYTTE", "BYTUR", "BYVIS", "BÅING", "BÅRET",
  "BÅTEN", "BÆRER", "BÆRÅR", "BÆSJE", "BØKER", "BØKLE", "BØLGE", "BØLLE", "BØNNE", "BØREK",
  "BØRNE", "BØRSE", "BØRST", "BØSSE", "BØTTE", "BØYES", "BØYET", "BØYLE", "CAMPE", "CARGO",
  "CASHE", "CASTE", "CELLE", "CELLO", "CESUR", "CHATT", "CHIEF", "CHILI", "CHIPS", "CHOKE",
  "CHUCK", "CIRKA", "COACH", "CONGA", "CORNY", "CORPS", "COVER", "COVRE", "CRACK", "CRAZY",
  "CREDO", "CREPE", "CROSS", "CULPA", "CURIE", "CURLE", "CYKEL", "CYSTE", "DABBE", "DACHS",
  "DADDA", "DADLE", "DAFFE", "DAGEN", "DAGES", "DAGNE", "DALBU", "DALEN", "DALER", "DALET",
  "DALIT", "DALKE", "DALLE", "DALTE", "DAMEN", "DAMPE", "DANDY", "DANKE", "DANNA", "DANNE",
  "DANSE", "DANSK", "DARRE", "DASKE", "DASSE", "DATEL", "DATID", "DATIV", "DATOR", "DATUM",
  "DAUDE", "DAVIT", "DEBET", "DEBIL", "DEBUT", "DECCA", "DEGGE", "DEILD", "DEISE", "DEIST",
  "DEITE", "DEKAN", "DEKAR", "DEKKE", "DEKOR", "DELER", "DELJE", "DELTA", "DEMME", "DEMON",
  "DEMPE", "DEMRE", "DENAR", "DENGE", "DENIM", "DENNE", "DEPOT", "DEPPA", "DEPPE", "DERAV",
  "DERBY", "DERES", "DEROM", "DERPÅ", "DERRE", "DESIM", "DESTO", "DETTE", "DEVON", "DEVOT",
  "DIARE", "DIDYM", "DIETT", "DIGEL", "DIGER", "DIGGE", "DIING", "DIKKE", "DIKTE", "DILDO",
  "DILLE", "DILTE", "DIMME", "DINAR", "DINER", "DINGO", "DINGS", "DINKA", "DIODE", "DIPOL",
  "DIRKE", "DIRRE", "DISET", "DISIG", "DISKE", "DISKO", "DISSE", "DITTO", "DIVAN", "DJERV",
  "DJINN", "DJUPN", "DOBBE", "DOBLE", "DOBRO", "DODGE", "DODRE", "DODØR", "DOGGE", "DOGME",
  "DOKKE", "DOLCE", "DOLKE", "DOLLE", "DOMRA", "DONNA", "DONOR", "DOPPE", "DORER", "DORGE",
  "DORME", "DORSK", "DOSER", "DOSIS", "DOTTE", "DOULA", "DOVEN", "DOVNE", "DOYEN", "DRADD",
  "DRAFT", "DRAGE", "DRAKE", "DRAKT", "DRAMA", "DRANK", "DRASS", "DRATT", "DRAUG", "DREGG",
  "DREIE", "DREIS", "DRENE", "DRENG", "DREPE", "DRESS", "DRETT", "DRIFT", "DRIKK", "DRIKS",
  "DRILL", "DRINK", "DRIVE", "DROGE", "DRONE", "DROPP", "DROPS", "DROTT", "DRUER", "DRUNT",
  "DRUSE", "DRYGE", "DRYLE", "DRYPP", "DRYSS", "DRÅPA", "DRÅPE", "DRÅTT", "DRØLE", "DRØNN",
  "DRØSE", "DRØSS", "DRØYE", "DUBBE", "DUBLE", "DUELL", "DUETE", "DUETT", "DUFTE", "DUGGE",
  "DUKAT", "DUKKE", "DULGT", "DULLE", "DULME", "DULPE", "DULTE", "DUMMA", "DUMME", "DUMMY",
  "DUMPE", "DUNET", "DUNGE", "DUNKE", "DUNSE", "DUNST", "DUPPE", "DURRA", "DUSEN", "DUSIN",
  "DUSJE", "DUSKE", "DUSTE", "DUSØR", "DUTTE", "DVALE", "DVASK", "DVEIL", "DVELE", "DVERG",
  "DYADE", "DYBDE", "DYDIG", "DYING", "DYKKE", "DYLLE", "DYNGE", "DYNKE", "DYPPE", "DYPÅL",
  "DYRKE", "DYSSE", "DYSTE", "DYTTE", "DYVÅT", "DÅDYR", "DÅSET", "DÆVEN", "DØDSE", "DØING",
  "DØLGE", "DØLSK", "DØMME", "DØNNE", "DØPER", "DØREN", "DØSEN", "DØSIG", "DØYVE", "EAGLE",
  "EBOLA", "EDDER", "EDDIK", "EDERS", "EDIKT", "EFUGL", "EGDSK", "EGGET", "EGLET", "EGNER",
  "EGNET", "EIDER", "EIGEN", "EIING", "EINER", "EIRET", "EITEL", "EITER", "EITRE", "EKALL",
  "EKKEL", "EKORN", "EKSEM", "EKSIL", "EKSIS", "EKSOS", "ELAND", "ELBIL", "ELDES", "ELDRE",
  "ELDST", "ELEGI", "ELGEN", "ELGKU", "ELING", "ELITE", "ELLER", "ELLOK", "ELOGE", "ELSKE",
  "ELVEN", "EMMEN", "EMOJI", "ENDER", "ENDIV", "ENDOG", "ENDRE", "ENGEL", "ENHET", "ENING",
  "ENKEL", "ENKET", "ENKOM", "ENORM", "ENROM", "ENSKE", "ENSOM", "ENTEN", "ENTRE", "ENVIS",
  "ENZYM", "ENØRE", "ENØYD", "EOCEN", "EPIKK", "EPISK", "EPLET", "EPOKE", "ERGRE", "ERTEN",
  "ERTET", "ERTOG", "ESING", "ESKER", "ESPRI", "ESSAY", "ESTER", "ESTET", "ETIKK", "ETING",
  "ETISK", "ETSER", "ETTER", "ETTID", "ETYDE", "EVDØL", "EVENT", "FABEL", "FABLE", "FACTS",
  "FADER", "FAGER", "FAGNE", "FAITE", "FAKIR", "FAKKE", "FAKLE", "FAKSE", "FAKTA", "FAKTE",
  "FALBY", "FALDE", "FALLE", "FALME", "FALSE", "FALSK", "FAMLE", "FAMØS", "FANCY", "FANGE",
  "FARAD", "FARAO", "FAREN", "FARGA", "FARGE", "FARIN", "FARKE", "FARSE", "FARSI", "FARTE",
  "FARVE", "FASAN", "FASIT", "FASLE", "FASTE", "FATAL", "FATLE", "FATTA", "FATTE", "FATUM",
  "FATWA", "FATØL", "FAUKE", "FAUNA", "FAVNE", "FAVØR", "FEAVL", "FEBER", "FECIT", "FEDDE",
  "FEDME", "FEFOT", "FEIDE", "FEIER", "FEIGD", "FEIKE", "FEILE", "FEIRE", "FEITE", "FEKAR",
  "FEKTE", "FELGE", "FELLE", "FELÅS", "FEMTE", "FEMTI", "FENAD", "FENGE", "FENOL", "FENYL",
  "FERDE", "FERGE", "FERIE", "FERJE", "FERME", "FERSK", "FERTE", "FESJÅ", "FESTE", "FETNE",
  "FIBER", "FIDUS", "FIFFE", "FIFLE", "FIGHT", "FIGUR", "FIKEN", "FIKLE", "FIKSE", "FIKTE",
  "FILER", "FILET", "FILLE", "FILME", "FILUR", "FINAL", "FINER", "FINIS", "FINKE", "FINNE",
  "FINSK", "FINTE", "FIRER", "FIRMA", "FISEN", "FISKE", "FISLE", "FISTE", "FJASE", "FJELG",
  "FJELL", "FJERN", "FJERT", "FJESK", "FJOLL", "FJOLS", "FJOMP", "FJONG", "FJORD", "FJOTT",
  "FJUSK", "FJÅSE", "FJÆRE", "FJØRE", "FLABB", "FLAGE", "FLAGG", "FLAKE", "FLAKK", "FLAKS",
  "FLANE", "FLAPS", "FLARE", "FLASH", "FLASK", "FLASS", "FLATE", "FLAUE", "FLEIP", "FLEIS",
  "FLEKK", "FLENG", "FLENS", "FLERE", "FLESK", "FLEST", "FLIDD", "FLIKK", "FLINK", "FLINT",
  "FLIPP", "FLIRE", "FLISE", "FLOKE", "FLOKK", "FLOKS", "FLOPP", "FLORA", "FLOSS", "FLOTT",
  "FLUEN", "FLUID", "FLUKS", "FLUKT", "FLUOR", "FLUSH", "FLUSK", "FLUSS", "FLUST", "FLYER",
  "FLYET", "FLYGE", "FLYTE", "FLÅER", "FLÅSE", "FLÅTE", "FLÅTT", "FLÆRE", "FLØKE", "FLØRT",
  "FLØTE", "FLØYT", "FNATT", "FNISE", "FNOKK", "FNUGG", "FNYSE", "FOAJE", "FOKAL", "FOKUS",
  "FOLAT", "FOLDE", "FOLIE", "FOLIO", "FOLKE", "FOLLE", "FOLNE", "FOMLE", "FONDS", "FONDY",
  "FONEM", "FONNE", "FORAN", "FORBI", "FORBY", "FORCE", "FORDI", "FORGI", "FORGÅ", "FORMA",
  "FORME", "FORMÅ", "FORRE", "FORSE", "FORST", "FORTA", "FORTE", "FORUM", "FORUT", "FORÅR",
  "FOSNA", "FOSSE", "FOTGÅ", "FOTON", "FRABE", "FRAGÅ", "FRAKK", "FRAKT", "FRAMT", "FRANC",
  "FRANK", "FRARÅ", "FRASE", "FRASI", "FRATA", "FREDA", "FREDE", "FREGE", "FREKK", "FRELS",
  "FREMT", "FREON", "FRESE", "FRIBY", "FRIER", "FRIGI", "FRISE", "FRISK", "FRIST", "FRITA",
  "FRIÅR", "FRONT", "FROSK", "FROST", "FRUKT", "FRYDE", "FRYKT", "FRYSE", "FRÅDE", "FRØSE",
  "FRØÅR", "FUKTE", "FUNKE", "FUNKY", "FURER", "FURET", "FURIE", "FURTE", "FUSEL", "FUSKE",
  "FUSSE", "FUTIL", "FUTTE", "FYING", "FYLDE", "FYLKE", "FYLLE", "FYMAT", "FYORD", "FYRIG",
  "FYROP", "FYRST", "FYSAK", "FYSEN", "FÅING", "FÅRET", "FÆLEN", "FÆLNE", "FÆRRE", "FØDER",
  "FØDES", "FØING", "FØLER", "FØLES", "FØLGE", "FØLLE", "FØNER", "FØNKY", "FØRER", "FØRST",
  "FØRTI", "FØYKE", "FØYSE", "GAFLE", "GAGNE", "GAGNS", "GAIDE", "GAKKE", "GALAN", "GALEI",
  "GALEN", "GALGE", "GALLA", "GALLE", "GALON", "GALTE", "GAMAN", "GAMBE", "GAMER", "GAMET",
  "GAMIN", "GAMLA", "GAMMA", "GAMME", "GAMPE", "GANDA", "GANDE", "GANER", "GANGE", "GANTE",
  "GAPEN", "GAPER", "GAPET", "GAPLE", "GARDE", "GARNE", "GARNI", "GARPE", "GARVA", "GARVE",
  "GASJE", "GASSE", "GASTA", "GATER", "GAUDA", "GAUGE", "GAUKE", "GAULE", "GAUME", "GAUPE",
  "GBAJA", "GEBET", "GEBYR", "GEHØR", "GEINE", "GEIPE", "GEIRE", "GEIST", "GEITA", "GEITE",
  "GEKKO", "GEMAL", "GEMEN", "GEMME", "GEMSE", "GENOM", "GENRE", "GENUS", "GEODE", "GETTO",
  "GEVIR", "GEVÆR", "GIDDE", "GIFTE", "GIGGE", "GILDE", "GILJE", "GIMPE", "GIPSE", "GIRET",
  "GISNE", "GISPE", "GISSE", "GITAR", "GITRE", "GIVER", "GJALL", "GJEKK", "GJELD", "GJENG",
  "GJEPE", "GJERD", "GJESP", "GJEST", "GJETE", "GJORD", "GJURE", "GJÆRE", "GJØDE", "GJØGL",
  "GJØLE", "GJØNE", "GJØRE", "GJØRS", "GLACE", "GLADE", "GLAFS", "GLANE", "GLANS", "GLAPP",
  "GLASS", "GLATT", "GLEDE", "GLEFS", "GLEPP", "GLETT", "GLIDE", "GLIMA", "GLIME", "GLIMT",
  "GLIOM", "GLIPE", "GLIPP", "GLIRE", "GLISE", "GLORE", "GLOSE", "GLOSS", "GLOVE", "GLUGG",
  "GLUNT", "GLØDE", "GLØGG", "GLØSE", "GLØTT", "GNAGE", "GNASK", "GNEIS", "GNELL", "GNIEN",
  "GNIER", "GNIRK", "GNISS", "GNIST", "GNOME", "GNURE", "GNÅLE", "GODTA", "GODTE", "GOJIM",
  "GOMBE", "GOMLE", "GOMME", "GONZO", "GOPLE", "GOTER", "GOUDA", "GRABB", "GRACE", "GRADE",
  "GRAND", "GRANN", "GRAPS", "GRASE", "GRAUT", "GRAVE", "GREBO", "GREEN", "GREIE", "GREIN",
  "GREIP", "GRELL", "GREND", "GRENE", "GREPA", "GRESK", "GRESS", "GREVE", "GRIBB", "GRIFF",
  "GRILL", "GRIME", "GRIND", "GRINE", "GRIPE", "GRISE", "GRISK", "GRJOT", "GROGG", "GROPE",
  "GROSS", "GRUAL", "GRUFF", "GRUFS", "GRUGG", "GRUKK", "GRUMS", "GRUNK", "GRUNN", "GRUSE",
  "GRUSK", "GRUVE", "GRYLE", "GRYNE", "GRYNT", "GRYTE", "GRÅLE", "GRÅNE", "GRÅOR", "GRÅTE",
  "GRÅTT", "GRØDE", "GRØFT", "GRØNN", "GRØNT", "GRØPP", "GRØSS", "GRØTE", "GUANO", "GUBBE",
  "GUFFE", "GUFSE", "GUGGE", "GUGLE", "GUIDE", "GULKE", "GULNE", "GULPE", "GUMMI", "GUNST",
  "GURPE", "GUSTE", "GYDJE", "GYGER", "GYLLE", "GYLNE", "GYLTE", "GYMME", "GYNGE", "GYSER",
  "GYSJE", "GYTJE", "GYVEL", "GÅING", "GÅTUR", "GÆLER", "GÆREN", "GÆRNE", "GÆÆRN", "GØYAL",
  "GØYSE", "HABIL", "HACKE", "HADSJ", "HAGEL", "HAGEN", "HAGER", "HAGLE", "HAIKE", "HAIKU",
  "HAING", "HAKEN", "HAKKA", "HAKKE", "HALAL", "HALLE", "HALLO", "HALMA", "HALON", "HALSE",
  "HALTE", "HALVE", "HALVT", "HAMBO", "HAMLE", "HAMNE", "HAMRE", "HAMSE", "HANDS", "HANEN",
  "HANKE", "HANSA", "HANSE", "HAPPY", "HARAM", "HAREM", "HAREN", "HARKE", "HARME", "HARPE",
  "HARPY", "HARRY", "HARSK", "HARVE", "HASJE", "HASPE", "HASTE", "HATER", "HATIG", "HATSK",
  "HAUGE", "HAUKE", "HAULD", "HAUSA", "HAVET", "HAVIS", "HAVNE", "HAVRE", "HAVÅL", "HEADE",
  "HEDDE", "HEDEN", "HEDER", "HEDRE", "HEDØL", "HEFTA", "HEFTE", "HEGDE", "HEGNE", "HEGRE",
  "HEILE", "HEILO", "HEIME", "HEINE", "HEISE", "HEITI", "HEKKE", "HEKLE", "HEKSE", "HEKTE",
  "HEKTO", "HELDE", "HELER", "HELGE", "HELLE", "HELOT", "HELSE", "HELST", "HELVT", "HEMME",
  "HEMPE", "HENAD", "HENDE", "HENDT", "HENGE", "HENGI", "HENNA", "HENNE", "HENRY", "HENTE",
  "HEPPE", "HERAV", "HERDA", "HERDE", "HERJA", "HERJE", "HERKE", "HERME", "HEROM", "HEROS",
  "HERPE", "HERPÅ", "HERRE", "HERSE", "HERTZ", "HESJE", "HESPE", "HETNE", "HETSE", "HETTE",
  "HEVDE", "HEVLE", "HEVNE", "HIGEN", "HIJAB", "HIKKE", "HIKST", "HILDE", "HILSE", "HIMLA",
  "HIMLE", "HINDI", "HINDU", "HINKE", "HINNE", "HINTE", "HIREN", "HIRSE", "HISSE", "HITRE",
  "HITTE", "HIVER", "HJALT", "HJELL", "HJELM", "HJELP", "HJORD", "HJORT", "HJULE", "HJUPE",
  "HOBBY", "HOCKE", "HODDE", "HODET", "HODØL", "HOFTE", "HOGGE", "HOGST", "HOLDE", "HOLDT",
  "HOLKE", "HOLME", "HOLNE", "HOMME", "HOMSE", "HONDA", "HOPPE", "HORDE", "HORSE", "HORST",
  "HOSTE", "HOUSE", "HOVDE", "HOVEL", "HOVEN", "HOVNE", "HUBRO", "HUFSE", "HUGAL", "HUGAV",
  "HUGGE", "HUGST", "HUGTA", "HUHEI", "HUKRE", "HULAG", "HULKE", "HULLE", "HUMAN", "HUMID",
  "HUMLE", "HUMOR", "HUMPE", "HUMRE", "HUMUL", "HUMUS", "HUMØR", "HUNDE", "HUNER", "HURPE",
  "HURRA", "HURRE", "HUSAR", "HUSET", "HUSKE", "HUSKY", "HUSKØ", "HUSLY", "HUTLE", "HUTRE",
  "HVALP", "HVASS", "HVELV", "HVESE", "HVETE", "HVILE", "HVINE", "HVISK", "HVITE", "HVITT",
  "HVORI", "HYBEL", "HYDRA", "HYENE", "HYETE", "HYGGE", "HYKLE", "HYLER", "HYLLE", "HYLSE",
  "HYMEN", "HYMNE", "HYNDE", "HYNNE", "HYPPE", "HYRDE", "HYSJE", "HYSSE", "HYTTE", "HÅLKE",
  "HÅNLE", "HÅNSK", "HÅPET", "HÅRET", "HÆRTA", "HØGDE", "HØGRE", "HØKER", "HØKRE", "HØLET",
  "HØLJE", "HØLKE", "HØNSE", "HØRER", "HØRES", "HØSTE", "HØVEL", "HØVLE", "HØVRE", "HØYBU",
  "HØYDE", "HØYMO", "HØYNE", "HØYRE", "HØYST", "HØYÅR", "ICING", "IDEAL", "IDENT", "IDEST",
  "IDIOM", "IDIOT", "IDYLL", "IFJOR", "IFØRE", "IGJEN", "IGUAN", "IHUGA", "IKTUS", "ILAND",
  "ILBUD", "ILDER", "ILDNE", "ILEGG", "ILING", "ILSKE", "ILSOM", "ILTER", "ILTOG", "IMAGE",
  "IMAGO", "IMENS", "IMMUN", "IMØTE", "INATT", "INDER", "INDIE", "INDRE", "INERT", "INFAM",
  "INFUS", "INGEN", "INNAD", "INNBE", "INNBO", "INNBU", "INNBY", "INNEN", "INNGI", "INNGÅ",
  "INNOM", "INNPÅ", "INNSE", "INNTA", "INNÅT", "INPUT", "INTET", "INTIM", "INTRO", "IRING",
  "IRISK", "IRONI", "IRRET", "ISAND", "ISBAD", "ISBAR", "ISBIL", "ISBIT", "ISBLÅ", "ISBOR",
  "ISBRE", "ISETE", "ISFOT", "ISFRI", "ISHAV", "ISHUD", "ISHUS", "ISING", "ISLAG", "ISLAM",
  "ISLOM", "ISNÅL", "ISOKO", "ISPIL", "ISRES", "ISTER", "ISTID", "ISØDE", "ISØKS", "IVDØL",
  "IVEVD", "IVRIG", "JABBE", "JAFSE", "JAGER", "JAGGU", "JAKKE", "JAKKU", "JAKTE", "JALLA",
  "JALME", "JAMBE", "JAMEN", "JAMME", "JAMNE", "JAMRE", "JAMTE", "JAORD", "JASKE", "JASSE",
  "JATTE", "JAVEL", "JAZZE", "JEANS", "JEGER", "JEKKE", "JELKE", "JEMTE", "JENKA", "JENKE",
  "JENTA", "JENTE", "JERPE", "JETTE", "JEVNE", "JIBBE", "JINGO", "JIPPO", "JOBBE", "JODID",
  "JODLE", "JOGGE", "JOGGU", "JOIKE", "JOKER", "JOKKE", "JOLLE", "JONER", "JORDE", "JORTE",
  "JOTUN", "JOULE", "JUBEL", "JUBLE", "JUDAS", "JUGLE", "JUICE", "JUKKE", "JUKSE", "JULLE",
  "JUMBO", "JUMPE", "JUNGE", "JUNKE", "JUNTA", "JURIS", "JUTUL", "JUVEL", "JÅLET", "JÆKEL",
  "JÆKLA", "JÆRBU", "JÆRSK", "JÆVEL", "JØGLE", "JØKEL", "KABAL", "KABBE", "KABEL", "KABIN",
  "KABLE", "KABYL", "KADER", "KAFFE", "KAFIR", "KAGGE", "KAJAL", "KAKAO", "KAKEN", "KAKKE",
  "KAKLE", "KAKSE", "KALAS", "KALIF", "KALKE", "KALLE", "KALUN", "KALVE", "KAMBA", "KAMEL",
  "KAMIN", "KAMME", "KAMSE", "KANAK", "KANAL", "KANEL", "KANIN", "KANNE", "KANON", "KANTE",
  "KAPER", "KAPOK", "KAPPE", "KAPRE", "KAPUN", "KARAT", "KARBO", "KARDE", "KAREN", "KARET",
  "KARGO", "KARIB", "KARMA", "KARPE", "KARRE", "KARRI", "KARSE", "KARSK", "KARTE", "KARVE",
  "KASKO", "KASSA", "KASSE", "KASTE", "KASUS", "KATAR", "KATER", "KATET", "KATTE", "KAUKE",
  "KAUSE", "KAVAI", "KAVET", "KAVLE", "KEBAB", "KEDIV", "KEFIR", "KEGEL", "KEIKE", "KEITE",
  "KEIVE", "KELAT", "KELIM", "KENDO", "KERAM", "KETON", "KHMER", "KIBBE", "KIKER", "KIKKE",
  "KIKNE", "KIKRE", "KIKSE", "KILDE", "KILEN", "KILER", "KILLE", "KIMSE", "KINGE", "KININ",
  "KINKE", "KINKS", "KINKY", "KINNE", "KIOSK", "KIPEN", "KIPER", "KIPPE", "KIRKE", "KISEL",
  "KISLE", "KISTE", "KITER", "KITIN", "KITLE", "KITTE", "KIVES", "KJAKE", "KJAKS", "KJAPP",
  "KJASE", "KJAVE", "KJEDE", "KJEFT", "KJEKK", "KJEKS", "KJELE", "KJEMI", "KJENG", "KJENT",
  "KJEPP", "KJERR", "KJERV", "KJESE", "KJESK", "KJEVE", "KJOKS", "KJOLE", "KJONE", "KJUKE",
  "KJÆLE", "KJÆRE", "KJÆTE", "KJØLD", "KJØLE", "KJØMD", "KJØNN", "KJØPE", "KJØRE", "KJØRT",
  "KJØTT", "KJØVE", "KLABB", "KLADD", "KLAFF", "KLAGE", "KLAKE", "KLAKK", "KLAMP", "KLANG",
  "KLANT", "KLAPP", "KLAPS", "KLARE", "KLART", "KLASE", "KLASK", "KLATT", "KLAUV", "KLAVE",
  "KLEBE", "KLEDE", "KLEGG", "KLEIE", "KLEIM", "KLEIN", "KLEIS", "KLEIV", "KLEKK", "KLEMT",
  "KLEPP", "KLERK", "KLESS", "KLETT", "KLEVE", "KLIEN", "KLIKK", "KLIMA", "KLINE", "KLING",
  "KLINK", "KLIPE", "KLIPP", "KLIPS", "KLIRR", "KLISS", "KLITT", "KLIVE", "KLODE", "KLOKE",
  "KLONE", "KLOPP", "KLORE", "KLOSS", "KLOVE", "KLOVN", "KLUBB", "KLUFT", "KLUKK", "KLUMP",
  "KLUMS", "KLUNK", "KLUNS", "KLURE", "KLUSS", "KLYNK", "KLYPE", "KLYSE", "KLYSS", "KLYVE",
  "KLÅTE", "KLØFT", "KLØKK", "KLØKT", "KLØNE", "KLØVE", "KLØYV", "KNABB", "KNAGG", "KNAKE",
  "KNAKK", "KNALL", "KNAPP", "KNAPT", "KNARK", "KNARR", "KNART", "KNASE", "KNASK", "KNAST",
  "KNATT", "KNAUS", "KNEGE", "KNEGG", "KNEGÅ", "KNEIK", "KNEKK", "KNEKT", "KNELE", "KNEPP",
  "KNERT", "KNEST", "KNETT", "KNIKS", "KNIPE", "KNIPS", "KNIRK", "KNISE", "KNISL", "KNIVE",
  "KNODE", "KNOGE", "KNOKE", "KNOLL", "KNOPE", "KNOPP", "KNORT", "KNOTE", "KNOTT", "KNUBB",
  "KNUGE", "KNULL", "KNULT", "KNUPP", "KNUPS", "KNURR", "KNURV", "KNUSE", "KNUSK", "KNUTE",
  "KNUTT", "KNUVL", "KNYST", "KNYTE", "KNØEN", "KNØTT", "KOAKS", "KOALA", "KOBBE", "KOBLE",
  "KOBRA", "KODDE", "KODER", "KOFTE", "KOGGE", "KOGLE", "KOINE", "KOKER", "KOKKE", "KOKOS",
  "KOKRE", "KOKSE", "KOLBE", "KOLIN", "KOLJE", "KOLLE", "KOLLI", "KOLON", "KOMET", "KOMMA",
  "KOMME", "KOMPE", "KOMSE", "KONGE", "KONGO", "KONKE", "KONSE", "KONTE", "KONTO", "KONUS",
  "KOPAL", "KOPEK", "KOPEN", "KOPLE", "KOPPE", "KOPRA", "KORAL", "KORAN", "KORDE", "KORKA",
  "KORKE", "KORNE", "KORNY", "KORPS", "KORSE", "KORTE", "KOSTE", "KOVNE", "KPELE", "KRAAL",
  "KRAFS", "KRAFT", "KRAGE", "KRAGG", "KRAKE", "KRAKK", "KRANE", "KRANK", "KRANS", "KRAPP",
  "KRASE", "KRASJ", "KRASL", "KRASS", "KRATT", "KRAVE", "KRAVL", "KREFT", "KREKE", "KRELE",
  "KREMT", "KREOL", "KREPP", "KREPS", "KRETI", "KRETS", "KREVE", "KRIGE", "KRILL", "KRIME",
  "KRING", "KRINK", "KRINS", "KRISE", "KRITE", "KRITT", "KROAT", "KROKE", "KROKI", "KRONE",
  "KROON", "KROPP", "KROTE", "KRUGG", "KRUKE", "KRULL", "KRUPP", "KRUSE", "KRUTT", "KRYMP",
  "KRYNE", "KRYPE", "KRYPT", "KRYSS", "KRÅKE", "KRÅLE", "KRØKE", "KRØLL", "KUBBE", "KUBEN",
  "KUBUS", "KUDOS", "KUFOR", "KUFTE", "KUHUD", "KUING", "KUJON", "KUJUR", "KULDE", "KULLE",
  "KULSE", "KULTE", "KULØR", "KUMLE", "KUMME", "KUMPE", "KUNDE", "KUNKE", "KUNNE", "KUNST",
  "KUPLE", "KUPPE", "KURER", "KURIE", "KURLE", "KURRE", "KURSE", "KURVE", "KUSKE", "KUSMA",
  "KUSTE", "KUTTE", "KUVEN", "KUVET", "KUØYE", "KVABB", "KVAKK", "KVALM", "KVANN", "KVANT",
  "KVAPS", "KVARE", "KVARG", "KVARK", "KVART", "KVARV", "KVASE", "KVASI", "KVASS", "KVAST",
  "KVEDE", "KVEGE", "KVEIK", "KVEIL", "KVEIN", "KVEIS", "KVEKE", "KVEKK", "KVELD", "KVELE",
  "KVELL", "KVELV", "KVEPP", "KVERK", "KVERN", "KVERV", "KVESE", "KVIDE", "KVIGE", "KVIKE",
  "KVIKK", "KVILE", "KVILT", "KVINE", "KVINK", "KVINT", "KVISE", "KVISS", "KVIST", "KVITE",
  "KVITT", "KVOTE", "KVÆVE", "KYLLE", "KYLNE", "KYNDE", "KYNNE", "KYRIE", "KYSSE", "KÅPEN",
  "KÅRDE", "KÅREN", "KÅSØR", "KØING", "KØLBY", "KØLET", "KØLLE", "KØLOS", "LABAN", "LABBE",
  "LABER", "LABIL", "LADDE", "LADEN", "LADER", "LAFTE", "LAGER", "LAGGE", "LAGJE", "LAGOM",
  "LAGRE", "LAING", "LAKEI", "LAKEN", "LAKKE", "LALLE", "LAMME", "LAMPE", "LANDE", "LANGE",
  "LANGO", "LANGS", "LANGT", "LANKE", "LANSE", "LAPIS", "LAPPE", "LARGO", "LARME", "LARVE",
  "LASER", "LASET", "LASKE", "LASSO", "LASTE", "LASUR", "LATEN", "LATIN", "LATTE", "LAUGE",
  "LAURE", "LAUVE", "LAVVO", "LEASE", "LEDDE", "LEDER", "LEDES", "LEDIG", "LEFLE", "LEFSE",
  "LEGAL", "LEGAT", "LEGDE", "LEGGE", "LEGIO", "LEIDE", "LEIER", "LEIES", "LEIKE", "LEING",
  "LEIRE", "LEITE", "LEIVD", "LEIVE", "LEKEN", "LEKER", "LEKKE", "LEKRE", "LEKSE", "LEKTE",
  "LEMEN", "LEMMA", "LEMME", "LEMPE", "LEMUR", "LEMUS", "LENDE", "LENGE", "LENGT", "LENKE",
  "LENSE", "LEPJE", "LEPPE", "LEPRA", "LERKE", "LESBE", "LESER", "LESKE", "LESPE", "LESSE",
  "LESTE", "LESTO", "LETER", "LETNE", "LETTE", "LEVEN", "LEVER", "LEVNE", "LEVRE", "LIGGE",
  "LIGHT", "LIGNE", "LIING", "LIKNE", "LIKSÅ", "LIKTÅ", "LIKØR", "LILJE", "LILLA", "LILLE",
  "LIMBA", "LIMBO", "LIMER", "LINDE", "LINGO", "LINJE", "LINKE", "LINKS", "LINNE", "LINON",
  "LINSE", "LIPID", "LIRKE", "LISSE", "LISTE", "LITAS", "LITEN", "LITER", "LITOT", "LIUNG",
  "LIVAT", "LIVER", "LIVNE", "LIVRE", "LJOME", "LJORE", "LJUGE", "LOBBE", "LOBBY", "LODDE",
  "LODEN", "LODJE", "LOETE", "LOFFE", "LOGGE", "LOGRE", "LOING", "LOJAL", "LOKAL", "LOKKE",
  "LOMME", "LOMPE", "LOMRE", "LOMVI", "LONGE", "LONGO", "LONGS", "LOOPE", "LOPPE", "LORAN",
  "LORJE", "LOSJE", "LOSJI", "LOSSE", "LOTTE", "LOTTO", "LOTUS", "LUBBE", "LUCIA", "LUFFE",
  "LUFTE", "LUGAR", "LUGGE", "LUGNE", "LUGOM", "LUGUM", "LUING", "LUKKE", "LUKTE", "LULLE",
  "LUMEN", "LUMPE", "LUMSK", "LUNCH", "LUNDE", "LUNET", "LUNGE", "LUNKE", "LUNNE", "LUNSJ",
  "LUNTE", "LUPIN", "LUPUS", "LURER", "LURKE", "LURVE", "LUSEN", "LUSET", "LUSKE", "LUTEN",
  "LUTRE", "LYBSK", "LYDIG", "LYING", "LYKKE", "LYKTE", "LYMFE", "LYNET", "LYNNE", "LYNOL",
  "LYSET", "LYSKE", "LYSNE", "LYSOL", "LYSTE", "LYSÅR", "LYTTE", "LÅNER", "LÅNTA", "LÅSEN",
  "LÅSER", "LÆGER", "LÆGRE", "LÆRER", "LØDIG", "LØFTE", "LØING", "LØKEN", "LØKKE", "LØNNA",
  "LØNNE", "LØNSK", "LØPER", "LØPSK", "LØRJE", "LØSEN", "LØSGI", "LØSNE", "LØYEN", "LØYER",
  "LØYND", "LØYNE", "LØYPE", "LØYSE", "LØYVE", "MACHO", "MADAM", "MAFIA", "MAGEN", "MAGER",
  "MAGGE", "MAGMA", "MAGRE", "MAHDI", "MAILE", "MAJOR", "MAKAK", "MAKEN", "MAKKE", "MAKKO",
  "MAKRO", "MAKSI", "MAKTE", "MALAY", "MALER", "MALJE", "MALLE", "MALME", "MALTE", "MAMBA",
  "MAMBO", "MAMMA", "MANER", "MANET", "MANGA", "MANGE", "MANGO", "MANKE", "MANKO", "MANNA",
  "MANNE", "MANSK", "MANUS", "MAORI", "MAPPE", "MARIN", "MARKI", "MARME", "MARSJ", "MARSK",
  "MASAI", "MASEN", "MASER", "MASET", "MASJI", "MASKE", "MASSE", "MASTE", "MATBU", "MATCH",
  "MATER", "MATKØ", "MATOS", "MATRO", "MATTE", "MAULE", "MAURE", "MAZDA", "MEDED", "MEDGI",
  "MEDGÅ", "MEDIO", "MEDOC", "MEGET", "MEGLE", "MEINE", "MEISE", "MEITE", "MEKKA", "MEKKE",
  "MEKLE", "MEKRE", "MELDE", "MELEN", "MELET", "MELIS", "MELKE", "MELLE", "MELON", "MELTE",
  "MENDE", "MENED", "MENGE", "MENIG", "MENTE", "MERKE", "MERLE", "MESAN", "MESEN", "MESKE",
  "MESON", "MESSE", "METAN", "METER", "METRO", "METTE", "METYL", "MEZZO", "MIDJE", "MIDLE",
  "MIDTE", "MIKSE", "MILJØ", "MILLE", "MIMRE", "MINKE", "MINNE", "MINST", "MINUS", "MISSE",
  "MISTA", "MISTE", "MITRA", "MJAUE", "MJELE", "MJUKE", "MJØDM", "MJØLE", "MJØLK", "MJØLL",
  "MOARE", "MOBBE", "MOBIL", "MODAL", "MODEM", "MODEN", "MODER", "MODIG", "MODNE", "MODUL",
  "MODUS", "MODØL", "MOGOP", "MOGUL", "MOING", "MOKKA", "MOLBO", "MOLDE", "MOLOK", "MOLTE",
  "MOLTO", "MOMPE", "MONNE", "MONOM", "MOPED", "MOPPE", "MORAL", "MOREN", "MORIN", "MORNA",
  "MORSE", "MORSK", "MOSET", "MOSKE", "MOTIV", "MOTOR", "MOTSI", "MOTTA", "MOTTO", "MUDRE",
  "MUFFE", "MUFTI", "MUGGE", "MUGNE", "MUKKE", "MULDE", "MULEN", "MULIG", "MULKT", "MULLA",
  "MULLE", "MULNE", "MULRE", "MULTE", "MUMIE", "MUMLE", "MUMSE", "MUNKE", "MUNNE", "MURER",
  "MURRE", "MUSAK", "MUSET", "MUSSE", "MYCEL", "MYGLE", "MYKIS", "MYKNE", "MYNDE", "MYNTE",
  "MYOPI", "MYOSE", "MYRDE", "MYRET", "MYRRA", "MYSKE", "MYSLI", "MÅKER", "MÅLER", "MÅNED",
  "MÅNEN", "MÅTTE", "MØBEL", "MØDIG", "MØDOM", "MØKKA", "MØKKE", "MØLJE", "MØLLE", "MØNJE",
  "MØRJE", "MØRKE", "MØRNE", "MØTES", "NABBE", "NABOB", "NADIR", "NAFTA", "NAGLE", "NAKEN",
  "NAKKE", "NAPPA", "NAPPE", "NARKO", "NARRE", "NASAL", "NASKE", "NATAL", "NATTE", "NATUR",
  "NAUBE", "NAUST", "NAVAR", "NAVLE", "NAVNE", "NEBBE", "NEDAD", "NEDOM", "NEDPÅ", "NEDRE",
  "NEGER", "NEGLE", "NEIDA", "NEIGU", "NEKTE", "NEMME", "NEMND", "NENNE", "NEPEN", "NEPPE",
  "NERTS", "NERVE", "NESBU", "NESEN", "NESLE", "NESTE", "NETTE", "NETTO", "NEVER", "NEVNE",
  "NGALA", "NIBBE", "NIDEL", "NIDSK", "NIESE", "NIKAB", "NIKKE", "NIKSE", "NIPPE", "NISJE",
  "NISSE", "NISTE", "NITEN", "NITID", "NITTE", "NITTI", "NIÅRS", "NIØYE", "NJORO", "NOBEL",
  "NODUL", "NOGEN", "NOKKE", "NOKSÅ", "NOMEN", "NONNE", "NORDI", "NORNE", "NORSK", "NOTAR",
  "NOTAT", "NOTIS", "NUBBE", "NUDDE", "NUDEL", "NUFSE", "NUGAT", "NUGGE", "NULLE", "NULTE",
  "NUPPE", "NUPRE", "NUSKE", "NUSLE", "NUSSE", "NUVET", "NYBÆR", "NYGLE", "NYHET", "NYING",
  "NYKKE", "NYLIG", "NYLON", "NYMFE", "NYNNE", "NYORD", "NYRIK", "NYSNØ", "NYTER", "NYTID",
  "NYTTE", "NYVEG", "NYVEI", "NYVLE", "NÅDIG", "NÅING", "NÅLYS", "NÅTID", "NÅTLE", "NÅVEL",
  "NÆRIG", "NÆRME", "NØDIG", "NØDÅR", "NØFFE", "NØING", "NØKKE", "NØLER", "NØSTE", "NØYEN",
  "NØYES", "NØYTE", "OASIS", "OBLAT", "OBLIK", "ODIØS", "OFFER", "OFRER", "OHMSK", "OIING",
  "OKAPI", "OKSID", "OKSYD", "OKTAN", "OKTAV", "OLDER", "OLDIS", "OLJET", "OLSOK", "OMBOT",
  "OMBUD", "OMDÅP", "OMEGA", "OMEGN", "OMFAR", "OMGÅS", "OMHUG", "OMLAG", "OMLYD", "OMLØP",
  "OMSUT", "OMSYN", "OMSØM", "OMVEG", "OMVEI", "ONANI", "ONING", "ONKEL", "ONKOS", "ONYKS",
  "OPART", "OPERA", "OPIAT", "OPIUM", "OPPAD", "OPPAL", "OPPBY", "OPPGI", "OPPNÅ", "OPPOM",
  "OPPSI", "OPPTA", "ORDEN", "ORDNE", "ORDRE", "ORGAN", "ORGEL", "ORGIE", "ORIGO", "ORKAN",
  "ORLOG", "ORLON", "ORLOV", "ORNAT", "OROMO", "OSEAN", "OSING", "OSMAN", "OTIUM", "OTTES",
  "OUNCE", "OVAPÅ", "OVERS", "PACER", "PADDE", "PADLE", "PADRE", "PAFFE", "PAGAI", "PAGAN",
  "PAKKE", "PAKTE", "PALLA", "PALME", "PAMPE", "PANDA", "PANEL", "PANIR", "PANNE", "PANTE",
  "PANTY", "PAPIR", "PAPPA", "PAPPE", "PARAT", "PARIA", "PARRE", "PARTI", "PARTY", "PASJA",
  "PASJE", "PASSE", "PASTA", "PATER", "PATOS", "PATTE", "PAUKE", "PAUSE", "PAVET", "PEDAL",
  "PEILE", "PEISE", "PEKER", "PELLE", "PELSE", "PENGE", "PENIS", "PENNE", "PENNI", "PENNY",
  "PENSE", "PEPRE", "PERLE", "PERSE", "PESTO", "PETIT", "PETUM", "PIANO", "PIECE", "PIFFE",
  "PIGGE", "PILAR", "PILKE", "PILLE", "PILOT", "PILTE", "PIMPE", "PINJE", "PINKE", "PINNE",
  "PINSE", "PINUP", "PIPER", "PIPET", "PIPLE", "PIPPE", "PIRAT", "PIREN", "PIRKE", "PIROG",
  "PIROL", "PIRRE", "PIRSE", "PIRUM", "PIRÅL", "PISKE", "PISSE", "PISTE", "PITLE", "PIVOT",
  "PIZZA", "PJALT", "PJANK", "PJATT", "PJOKK", "PJOTE", "PJUSK", "PLAFF", "PLAGE", "PLAGG",
  "PLAKK", "PLANE", "PLANK", "PLASK", "PLASS", "PLAST", "PLATE", "PLATT", "PLATÅ", "PLEBS",
  "PLEDD", "PLEIE", "PLENT", "PLETI", "PLETT", "PLIKT", "PLING", "PLINT", "PLIRE", "PLITT",
  "PLOGE", "PLOPP", "PLOTT", "PLUGG", "PLUKK", "PLUMP", "PLUSS", "PLYSJ", "PLØSE", "PLØYE",
  "POENG", "POESI", "POKAL", "POKER", "POKKA", "POKRE", "POLAR", "POLIO", "POLIS", "POLKA",
  "POLKØ", "POLSK", "POLÆR", "POMOR", "PONNI", "POPPE", "PORET", "PORNO", "PORTO", "PORØS",
  "POSEN", "POSET", "POSTE", "POSØR", "POTET", "POTTE", "PRAIE", "PRAKK", "PRAKT", "PRALE",
  "PRATE", "PREGE", "PREKE", "PRENT", "PRESS", "PREST", "PRIAR", "PRIDE", "PRIKK", "PRIMA",
  "PRIME", "PRIMO", "PRINS", "PRIOR", "PRISE", "PROFF", "PROMP", "PROPP", "PROPS", "PROSA",
  "PROST", "PROVE", "PROVO", "PRUNK", "PRUPP", "PRUST", "PRUTE", "PRYDE", "PRYLE", "PRØVE",
  "PSYKE", "PTROE", "PUBES", "PUDLE", "PUDRE", "PUFFE", "PUGER", "PUGGE", "PUKKA", "PUKKE",
  "PULJE", "PULPA", "PULSE", "PUMPE", "PUMPS", "PUNCH", "PUNER", "PUNGE", "PUNKT", "PUNSJ",
  "PUPPE", "PURDA", "PURIN", "PURKE", "PURLE", "PURRE", "PUSET", "PUSHE", "PUSLE", "PUSSA",
  "PUSSE", "PUSTE", "PUTER", "PUTLE", "PUTRE", "PUTTE", "PUTTO", "PYGME", "PYNTE", "PYORE",
  "PYSEN", "PYSET", "PYTON", "PÅBUD", "PÅDRA", "PÅHØR", "PÅSKE", "PÅSTÅ", "PÅSYN", "PÅTÅR",
  "PÅVER", "PÆLME", "PÆREN", "PØBEL", "PØBLE", "PØLLE", "PØLSE", "PØNAL", "PØNSE", "QUART",
  "QUILT", "QUIPU", "RABBE", "RABBI", "RABID", "RABLE", "RACER", "RADAR", "RADDE", "RADIG",
  "RADIO", "RADOM", "RADON", "RAFSE", "RAFTE", "RAGGE", "RAIDE", "RAKKE", "RAKLE", "RAKNE",
  "RAKST", "RALLE", "RALLY", "RAMLE", "RAMME", "RAMPE", "RAMSE", "RANCH", "RANDE", "RANER",
  "RANGE", "RANKE", "RAPER", "RAPID", "RAPPE", "RAPSE", "RASKE", "RASLE", "RASPE", "RASTE",
  "RATIO", "RATLE", "RATSJ", "RATTE", "RAUDA", "RAUKE", "RAUSE", "RAUTE", "RAYON", "REBUS",
  "REDDE", "REDER", "REDIG", "REELL", "REFSE", "REGAL", "REGEL", "REGLE", "REGNE", "REIKE",
  "REILE", "REING", "REINT", "REIPE", "REISE", "REIVE", "REKEL", "REKER", "REKKE", "REKST",
  "REKYL", "REMIS", "REMJE", "REMSE", "RENKE", "RENNE", "RENSE", "RENSK", "RENTE", "REPOS",
  "REPRO", "RESER", "RESIN", "RETOR", "RETTE", "RETUR", "REVEN", "REVIR", "REVLE", "REVNE",
  "RIBBE", "RIFLE", "RIGEL", "RIGGE", "RIGID", "RIGOR", "RIING", "RIJAL", "RIKKE", "RIKLE",
  "RIKSE", "RIKTE", "RILLE", "RIMER", "RIMET", "RINGE", "RINNE", "RIPET", "RIPPE", "RISKE",
  "RISLE", "RISPE", "RISSE", "RISTE", "RITSJ", "RITUS", "RIVAL", "ROBBE", "ROBOT", "ROBÅT",
  "ROCKA", "ROCKE", "RODEL", "RODEO", "ROING", "ROKKE", "ROLIG", "ROLLE", "ROMAN", "ROMBE",
  "ROMER", "ROMME", "ROMPE", "ROMSK", "RONDO", "RORBU", "ROSEN", "ROSET", "ROSIN", "ROSSE",
  "ROSTE", "ROTEN", "ROTER", "ROTET", "ROTOR", "ROTTE", "ROTUR", "ROUGE", "ROUGH", "ROVER",
  "RUBBE", "RUBEL", "RUBIN", "RUFFE", "RUFSE", "RUGBY", "RUGDE", "RUGER", "RUGGE", "RUGLE",
  "RUING", "RUKKE", "RUKLE", "RULLE", "RULTE", "RUMBA", "RUMLE", "RUMPE", "RUNDE", "RUNDI",
  "RUNDT", "RUNGE", "RUNKE", "RUNNE", "RUNSE", "RURAL", "RUSHE", "RUSKE", "RUSLE", "RUSTE",
  "RUTER", "RUTET", "RUTLE", "RUTTE", "RYDDE", "RYGER", "RYGGE", "RYING", "RYKKE", "RYKTE",
  "RYNKE", "RYSJE", "RYSTE", "RYTME", "RÅDGI", "RÅDIG", "RÅDYR", "RÅHET", "RÅING", "RÅMEN",
  "RÅNER", "RÅNET", "RÅSKE", "RÅTEV", "RÅTNE", "RÅVÆR", "RØDME", "RØDNE", "RØDÅT", "RØFLE",
  "RØFTE", "RØKER", "RØKJE", "RØKTE", "RØLPE", "RØMME", "RØNNE", "RØRER", "RØRET", "RØRIG",
  "RØSKE", "RØSTE", "RØVER", "RØYKE", "RØYND", "RØYNE", "RØYSE", "RØYTE", "SABBE", "SABEL",
  "SABLA", "SABLE", "SABRA", "SADEL", "SADLE", "SAFIR", "SAFTE", "SAGER", "SAGMO", "SAHIB",
  "SAIGA", "SAKHA", "SAKKE", "SAKNE", "SAKSE", "SAKTE", "SALAT", "SALDO", "SALET", "SALIG",
  "SALME", "SALSA", "SALTE", "SALTO", "SALVE", "SALÆR", "SAMBA", "SAMBO", "SAMBU", "SAMLE",
  "SAMME", "SAMRÅ", "SAMSE", "SANDE", "SANKE", "SANKT", "SANNE", "SANSE", "SAPPE", "SARMA",
  "SATAN", "SATSE", "SATYR", "SAUAL", "SAUEN", "SAUNA", "SAUSE", "SAUTE", "SAVLE", "SAVNE",
  "SCENE", "SCOOP", "SCORE", "SEBRA", "SEDAN", "SEDAT", "SEDER", "SEEDE", "SEFYR", "SEGLE",
  "SEGNE", "SEIDE", "SEIER", "SEIFE", "SEILE", "SEING", "SEIPE", "SEIRE", "SEISE", "SEKEL",
  "SEKSA", "SEKST", "SELEN", "SELGE", "SELJE", "SELLA", "SELLE", "SELOT", "SELVE", "SEMIN",
  "SEMJE", "SENAT", "SENDE", "SENET", "SENIL", "SENIT", "SENKE", "SENNA", "SENSE", "SEPIA",
  "SEPOY", "SERAF", "SERAI", "SERIE", "SERUM", "SERVE", "SERØS", "SESAM", "SESSE", "SETER",
  "SETRE", "SETTE", "SEVJE", "SEXUS", "SFÆRE", "SHAKE", "SHELF", "SHORT", "SHOWE", "SHUNT",
  "SIDDE", "SIDEN", "SIDER", "SIGAR", "SIGEN", "SIGGE", "SIGMA", "SIGNE", "SIING", "SIKLE",
  "SIKRE", "SIKTE", "SILDE", "SILKE", "SILUR", "SIMLE", "SIMPE", "SINDI", "SINKE", "SINNA",
  "SINNE", "SINUS", "SIOUX", "SIPET", "SIPPE", "SIRAT", "SIRKA", "SIRUP", "SISAL", "SISEL",
  "SISIK", "SISLE", "SITAR", "SITAT", "SITER", "SITRE", "SITTE", "SITUP", "SIVIL", "SIVÅT",
  "SJAKK", "SJAKO", "SJAKT", "SJALU", "SJAPP", "SJARK", "SJARM", "SJASK", "SJAUE", "SJEFE",
  "SJEIK", "SJEKK", "SJETE", "SJIKT", "SJOGE", "SJOGS", "SJOKK", "SJONA", "SJUER", "SJUKE",
  "SJUSK", "SJÅKE", "SJØBU", "SJØEN", "SJØIS", "SJØKU", "SKABB", "SKADE", "SKAFT", "SKAGE",
  "SKAKE", "SKAKK", "SKALA", "SKALD", "SKALK", "SKALL", "SKALP", "SKANK", "SKANN", "SKANT",
  "SKAPE", "SKARE", "SKARK", "SKARN", "SKARP", "SKARV", "SKATE", "SKATT", "SKAUT", "SKAVE",
  "SKAVL", "SKEET", "SKEID", "SKEIE", "SKEIS", "SKEIV", "SKIFT", "SKIKK", "SKILL", "SKILT",
  "SKIMT", "SKINN", "SKIPE", "SKIPP", "SKIRE", "SKITA", "SKITE", "SKITT", "SKIVE", "SKJEN",
  "SKJEV", "SKJOR", "SKJUL", "SKJÆR", "SKJØD", "SKJØR", "SKJØT", "SKLIE", "SKODA", "SKOFT",
  "SKOKK", "SKOLE", "SKOLM", "SKOLP", "SKOLT", "SKORT", "SKOSE", "SKOTT", "SKOVE", "SKOVL",
  "SKRAL", "SKRAP", "SKRED", "SKREI", "SKREV", "SKRIE", "SKRIK", "SKRIN", "SKRIV", "SKROG",
  "SKROT", "SKROV", "SKRUD", "SKRUE", "SKRUV", "SKRYT", "SKRÅL", "SKRÅS", "SKRØN", "SKUBB",
  "SKUDD", "SKUFF", "SKULE", "SKULK", "SKULS", "SKUMP", "SKUNK", "SKURD", "SKURE", "SKURK",
  "SKURV", "SKUTE", "SKUTT", "SKVAL", "SKVIP", "SKVIS", "SKVÆR", "SKYEN", "SKYET", "SKYGG",
  "SKYLD", "SKYLL", "SKYRU", "SKYSS", "SKYTE", "SKYTS", "SKYVE", "SKÅLD", "SKÅLE", "SKÅNE",
  "SKÅRE", "SKÅTE", "SKØYE", "SLABB", "SLADD", "SLAFS", "SLAGE", "SLAGG", "SLAGS", "SLAKK",
  "SLAKT", "SLAMP", "SLAMS", "SLANG", "SLANK", "SLANT", "SLAPP", "SLAPS", "SLARK", "SLARV",
  "SLASK", "SLAUR", "SLAVE", "SLEDE", "SLEID", "SLEIK", "SLEIP", "SLEIS", "SLEIV", "SLEKT",
  "SLENG", "SLEPE", "SLEPP", "SLESK", "SLETT", "SLEVE", "SLIDE", "SLIKK", "SLIKT", "SLIME",
  "SLIND", "SLIPE", "SLIPP", "SLIPS", "SLIRE", "SLISK", "SLITE", "SLITT", "SLIUL", "SLODD",
  "SLOTT", "SLUDD", "SLUFS", "SLUKE", "SLUKT", "SLUMP", "SLUMS", "SLUPP", "SLUPS", "SLURE",
  "SLURK", "SLURP", "SLURV", "SLUSE", "SLUSK", "SLUTT", "SLYET", "SLYNG", "SLÅPE", "SLÅSS",
  "SLÅTT", "SLØKE", "SLØRE", "SLØSE", "SLØVE", "SLØYD", "SLØYE", "SMAKE", "SMALE", "SMART",
  "SMASH", "SMASK", "SMATT", "SMEDE", "SMEIK", "SMEIS", "SMEKK", "SMELL", "SMIKK", "SMILE",
  "SMISK", "SMITT", "SMOKK", "SMOLT", "SMUDI", "SMUKK", "SMULE", "SMULT", "SMURF", "SMUSS",
  "SMUTT", "SMYGE", "SMYLE", "SMÅBY", "SMÅEN", "SMÅFE", "SMÅIS", "SMØRE", "SMØYE", "SNABB",
  "SNADD", "SNAFS", "SNAKE", "SNAKK", "SNAKS", "SNAPP", "SNAPS", "SNARE", "SNARP", "SNART",
  "SNASK", "SNAUE", "SNAVL", "SNEGL", "SNEIE", "SNEIP", "SNEIS", "SNEKE", "SNELL", "SNERK",
  "SNERP", "SNERR", "SNERT", "SNIKE", "SNILE", "SNILL", "SNIPE", "SNIPP", "SNITT", "SNIVE",
  "SNOBB", "SNOKE", "SNOPE", "SNORK", "SNOTT", "SNUFS", "SNUFT", "SNUPP", "SNUPT", "SNURP",
  "SNURR", "SNURT", "SNUSE", "SNUSK", "SNUTE", "SNUTT", "SNYTA", "SNYTE", "SNYTT", "SNÅLE",
  "SNÅVE", "SNØEN", "SNØET", "SNØFT", "SNØGG", "SNØIS", "SNØRE", "SNØRR", "SNØSE", "SNØVL",
  "SNØYE", "SNØÅR", "SOARE", "SOBEL", "SOBER", "SOGNE", "SOKKE", "SOKNE", "SOLAR", "SOLEN",
  "SOLID", "SOLUR", "SOLÅR", "SOMLE", "SOMME", "SONAR", "SONDE", "SONOR", "SOPEN", "SOPER",
  "SOPPE", "SORBE", "SORRY", "SORTI", "SOSET", "SOTET", "SOTHO", "SOUND", "SOVER", "SOVNE",
  "SPADE", "SPANE", "SPANN", "SPANT", "SPARE", "SPARK", "SPASE", "SPATT", "SPEED", "SPEIL",
  "SPEKE", "SPEKK", "SPEKS", "SPELL", "SPELT", "SPENE", "SPENN", "SPENT", "SPETT", "SPIDD",
  "SPIKA", "SPIKE", "SPIKK", "SPILE", "SPILL", "SPILT", "SPINK", "SPINN", "SPION", "SPIRE",
  "SPISE", "SPISK", "SPISS", "SPJÅK", "SPJÆR", "SPLID", "SPOLE", "SPONG", "SPORD", "SPORE",
  "SPORT", "SPOTT", "SPOVE", "SPRAK", "SPRAY", "SPREK", "SPRIK", "SPRIT", "SPROG", "SPRUT",
  "SPRYD", "SPRÅK", "SPRØE", "SPUNS", "SPURT", "SPURV", "SPYLE", "SPYTT", "SPØKE", "SPØLE",
  "SPØTE", "SPØTT", "SQUAW", "STADE", "STAGE", "STAKE", "STAKK", "STALL", "STAMP", "STAND",
  "STANE", "STANG", "STANK", "STANS", "STAPP", "STARE", "STARR", "START", "STASE", "STAUP",
  "STAUR", "STAUT", "STAVE", "STAVN", "STEAM", "STEDE", "STEGE", "STEGG", "STEIK", "STEIL",
  "STEIN", "STEKE", "STEKK", "STELE", "STELL", "STENG", "STENK", "STENT", "STERK", "STETT",
  "STEVN", "STIFT", "STIGE", "STIKK", "STILE", "STILK", "STILL", "STIME", "STING", "STINN",
  "STIRR", "STIVE", "STODE", "STOFF", "STOGG", "STOKK", "STOLA", "STOLE", "STOLL", "STOLT",
  "STOMP", "STOPP", "STORE", "STORK", "STORM", "STORY", "STOVE", "STRAK", "STRAM", "STREK",
  "STREV", "STRID", "STRIE", "STRIL", "STRUT", "STRYK", "STRÅL", "STRØK", "STRØM", "STUBB",
  "STUER", "STUKE", "STUKK", "STULL", "STUMP", "STUND", "STUNT", "STUPA", "STUPE", "STURE",
  "STUSS", "STUTT", "STYGG", "STYKK", "STYLE", "STYRE", "STYRT", "STÅKE", "STØKK", "STØLE",
  "STØNN", "STØPE", "STØTE", "STØTT", "STØVE", "STØYE", "STØYP", "STØYT", "SUBBE", "SUBUS",
  "SUGEN", "SUGER", "SUGGE", "SUITE", "SUKAT", "SUKKE", "SUKLE", "SUKRE", "SULKE", "SULKY",
  "SULLE", "SULRE", "SULTE", "SUMAK", "SUMME", "SUNNA", "SUNNI", "SUPER", "SUPPE", "SURFE",
  "SURLE", "SURNE", "SURRE", "SUSER", "SUSET", "SUSHI", "SUSLE", "SUSSE", "SUTRE", "SUTTE",
  "SUTUR", "SVADA", "SVAGE", "SVAIE", "SVAKE", "SVALE", "SVAMP", "SVANE", "SVANG", "SVANS",
  "SVARE", "SVART", "SVARV", "SVATI", "SVEAR", "SVEIG", "SVEIN", "SVEIP", "SVEIS", "SVEIT",
  "SVEIV", "SVEKK", "SVELE", "SVELG", "SVELL", "SVENN", "SVEPE", "SVERD", "SVERM", "SVETT",
  "SVEVE", "SVIKE", "SVIKT", "SVILL", "SVIME", "SVINE", "SVING", "SVINN", "SVINT", "SVIPE",
  "SVIPP", "SVIRE", "SVIVE", "SVOLK", "SVULL", "SVUPP", "SVÆVE", "SVØPE", "SWAZI", "SWING",
  "SYDPÅ", "SYING", "SYKLE", "SYKNE", "SYLFE", "SYLTA", "SYLTE", "SYMRE", "SYNDE", "SYNES",
  "SYNGE", "SYNKE", "SYNSE", "SYNSK", "SYNÅL", "SYRER", "SYRIN", "SYRNE", "SYROM", "SYSLE",
  "SYTEN", "SYTER", "SYTET", "SYTTI", "SYTØY", "SYVER", "SÅDAN", "SÅFRØ", "SÅGAR", "SÅING",
  "SÅLDE", "SÅTID", "SÅVEL", "SÆLDE", "SÆRBO", "SÆRBU", "SØDME", "SØKEN", "SØKER", "SØKKE",
  "SØLET", "SØLJE", "SØMME", "SØNNA", "SØPLE", "SØREN", "SØRGE", "SØRPE", "SØRPÅ", "SØRVE",
  "SØTEN", "SØVNE", "SØYLE", "TABBE", "TABLÅ", "TAFSE", "TAGAL", "TAGGE", "TAGNE", "TAIGA",
  "TAIME", "TAKET", "TAKKE", "TAKLE", "TAKSE", "TAKST", "TAKÅS", "TALER", "TALGE", "TALJE",
  "TALLE", "TALLY", "TAMFE", "TAMIL", "TAMPE", "TAMSE", "TANGA", "TANGE", "TANGO", "TANKE",
  "TANKS", "TANNE", "TANTE", "TAPAS", "TAPER", "TAPET", "TAPIR", "TAPPE", "TARVE", "TASAL",
  "TASET", "TASKE", "TASLE", "TASSE", "TASTE", "TATAR", "TATER", "TATLE", "TAUER", "TAVLE",
  "TEDDY", "TEFAT", "TEFTE", "TEGNE", "TEHUS", "TEINE", "TEING", "TEINT", "TEIPE", "TEIST",
  "TEITE", "TEKKE", "TEKNO", "TEKST", "TELET", "TELLE", "TELNE", "TELTE", "TELYS", "TEMME",
  "TEMNE", "TEMPO", "TENAR", "TENKE", "TENKT", "TENNE", "TENOR", "TENÅR", "TEORI", "TEPPE",
  "TERGE", "TERME", "TERNE", "TERPE", "TERRA", "TERSE", "TERTE", "TESIL", "TESLA", "TESTE",
  "TETNE", "TETTE", "TEVLE", "TEXAS", "THORN", "TIARA", "TIDEL", "TIDIG", "TIGER", "TIGGE",
  "TIGRE", "TIING", "TIKKE", "TILBE", "TILBY", "TILDE", "TILGI", "TILGÅ", "TILJE", "TILLE",
  "TILRÅ", "TILSE", "TILSI", "TILSÅ", "TILTA", "TILTE", "TIMEN", "TIMES", "TIMID", "TINDE",
  "TINER", "TINGE", "TINNE", "TINTE", "TIPLE", "TIPPE", "TIPSE", "TIRRE", "TISKE", "TISLE",
  "TISPE", "TISSE", "TITAN", "TITID", "TITTE", "TIÅRS", "TIØRE", "TJAFS", "TJALK", "TJATT",
  "TJELD", "TJENE", "TJERN", "TJONE", "TJORE", "TJUKK", "TJUKN", "TJUVE", "TJÅKE", "TJÆRE",
  "TOAST", "TOBBE", "TOBIS", "TODDI", "TODDY", "TOENE", "TOFTE", "TOGET", "TOING", "TOKAR",
  "TOKKE", "TOKTE", "TOLAR", "TOLKE", "TOLLE", "TOMAT", "TOMME", "TOMSE", "TOMTE", "TONAL",
  "TONEM", "TONUS", "TOPAS", "TOPPE", "TORSK", "TORSO", "TORVE", "TOSSE", "TOTAL", "TOTEM",
  "TOTID", "TOUCH", "TOVEN", "TOVET", "TOÅRS", "TOØRE", "TRABI", "TRACE", "TRADE", "TRAFO",
  "TRAKE", "TRAKK", "TRAKT", "TRALE", "TRALL", "TRALT", "TRAMP", "TRANE", "TRANG", "TRANT",
  "TRAPP", "TRASE", "TRASK", "TRASS", "TRAUD", "TRAVE", "TREAK", "TREDE", "TREEN", "TREER",
  "TREET", "TREFF", "TREGE", "TREIG", "TREKK", "TRELL", "TREMA", "TREND", "TRENE", "TRESK",
  "TRESS", "TRETT", "TREVE", "TREVL", "TRIAL", "TRIAS", "TRIKK", "TRIKS", "TRILL", "TRINE",
  "TRINN", "TRIOL", "TRIPP", "TRIPS", "TRISE", "TRIST", "TRITT", "TRIVE", "TROFE", "TROKE",
  "TROLL", "TRONE", "TROPE", "TROPP", "TROSS", "TROST", "TRUCK", "TRUEN", "TRUGE", "TRUMF",
  "TRUMP", "TRUNK", "TRUPP", "TRUSE", "TRUST", "TRUTT", "TRYGD", "TRYGG", "TRYKK", "TRYKT",
  "TRYNE", "TRYTE", "TRÅDE", "TRÅEN", "TRÅKK", "TRÅLE", "TRÆLE", "TRØKK", "TRØSK", "TRØST",
  "TRØTT", "TRØYE", "TRØYT", "TSJIN", "TUETE", "TUFSE", "TUFTE", "TUGGE", "TUKAN", "TUKLE",
  "TUKTE", "TULLE", "TUMLE", "TUMOR", "TUNER", "TUNGE", "TUNIA", "TUPPE", "TURBO", "TUREN",
  "TURNE", "TURVE", "TUSEN", "TUSJE", "TUSKE", "TUSLE", "TUSSE", "TUSTE", "TUTEL", "TUTLE",
  "TUTOR", "TUTSI", "TUTTE", "TUTTI", "TVANG", "TVARE", "TVEBO", "TVEBU", "TVERR", "TVERS",
  "TVERT", "TVETT", "TVILE", "TVILL", "TVINN", "TVIST", "TVÆRE", "TWEED", "TWIST", "TYDER",
  "TYFON", "TYFUS", "TYFØS", "TYGGE", "TYING", "TYKKE", "TYKNE", "TYLFT", "TYLLE", "TYMIN",
  "TYMUS", "TYNGE", "TYNNE", "TYPUS", "TYSSE", "TYSTE", "TYTTE", "TYVED", "TYVJO", "TÅFIS",
  "TÅGET", "TÅKET", "TÅLIG", "TÅPEN", "TÅRET", "TÅRNE", "TØFFE", "TØFLE", "TØING", "TØLER",
  "TØMME", "TØMRE", "TØNNE", "TØRKE", "TØRNE", "TØRRE", "TØRST", "TØSET", "TØTSJ", "TØTTE",
  "TØVER", "TØVET", "TØVÆR", "TØYLE", "TØYSE", "TØYTE", "UANET", "UBEDT", "UBEST", "UBLID",
  "UBLYG", "UBONA", "UBONT", "UBYGD", "UBØYD", "UDEKT", "UDELT", "UDRYG", "UDRØY", "UDØPT",
  "UEDEL", "UEGNA", "UEKTE", "UENIG", "UFIKS", "UFISK", "UFORA", "UFRED", "UFSET", "UFYSE",
  "UFØDT", "UFØRE", "UGAGN", "UGGEN", "UGGET", "UGIFT", "UGILD", "UGLAD", "UGRAS", "UGREI",
  "UGRER", "UHEIL", "UHELL", "UHUGA", "UHYRE", "UHØRT", "UIGUR", "UJAMN", "UJEVN", "UKENE",
  "UKLAR", "UKLOK", "UKOKT", "UKYSK", "ULADA", "ULADD", "ULAGE", "ULEST", "ULEVD", "ULIKE",
  "ULING", "ULLEN", "ULLUS", "ULVEN", "ULYST", "ULÅST", "ULÆRD", "ULÆRT", "ULØNT", "ULØST",
  "UMAKE", "UMALT", "UMAMI", "UMBRA", "UMIAK", "UMILD", "UMÅLT", "UMÅTE", "UNAVN", "UNDAS",
  "UNDER", "UNDRE", "UNETT", "UNION", "UNNBE", "UNNGÅ", "UNNSE", "UNNSI", "UNNTA", "UNOTE",
  "UNÅDE", "UPARA", "UPOPP", "UPRIS", "URAKA", "URBAN", "URDYR", "UREDD", "UREDE", "UREID",
  "UREIN", "UREMI", "URETE", "URETT", "URTID", "URUND", "URVEN", "URØKT", "URØRT", "USAGT",
  "USAMD", "USAMS", "USANN", "USETT", "USEXY", "USKAP", "USMAK", "USONA", "USONT", "USSEL",
  "USUNN", "USYDD", "USYRA", "USYRT", "USÅDD", "USÅRA", "USÆLE", "USØKT", "USØTA", "UTAKK",
  "UTAKT", "UTALL", "UTAPÅ", "UTARM", "UTARV", "UTASA", "UTAST", "UTBRE", "UTBUD", "UTDØR",
  "UTEDO", "UTEKK", "UTEMT", "UTETT", "UTFOR", "UTFRI", "UTHUS", "UTINA", "UTING", "UTINT",
  "UTKIK", "UTKOK", "UTLEG", "UTLYD", "UTLÅN", "UTLØE", "UTLØP", "UTMED", "UTMÅL", "UTOEN",
  "UTOPI", "UTROP", "UTROR", "UTSIG", "UTSTÅ", "UTSYN", "UTSÆD", "UTTAK", "UTTOG", "UTTUR",
  "UTUKT", "UTVED", "UTVEG", "UTVEI", "UTVÆR", "UTYSK", "UTØSE", "UTØVE", "UVANE", "UVANT",
  "UVDØL", "UVENN", "UVETT", "UVISS", "UÅPNA", "UØVET", "VABBE", "VABLE", "VADER", "VADRE",
  "VAFLE", "VAGGE", "VAGLE", "VAIER", "VAING", "VAKEN", "VAKER", "VAKLE", "VAKNE", "VAKRE",
  "VAKTE", "VALEN", "VALID", "VALKE", "VALLE", "VALMA", "VALME", "VALNE", "VALPE", "VALSE",
  "VALTE", "VALØR", "VANDE", "VANGE", "VANKE", "VANNE", "VANRY", "VANTE", "VARAN", "VARDE",
  "VARIA", "VARIG", "VARME", "VARPE", "VARTE", "VASET", "VASKE", "VASLE", "VASSE", "VATER",
  "VATNE", "VATRE", "VAVRE", "VEBBE", "VEDBU", "VEDDA", "VEDDE", "VEDGÅ", "VEDTA", "VEFTE",
  "VEGAN", "VEGNE", "VEGRE", "VEIDE", "VEIDN", "VEIEN", "VEIER", "VEIKE", "VEILE", "VEITE",
  "VEIVE", "VEKKE", "VEKNE", "VEKST", "VEKTE", "VELAR", "VELDE", "VELGE", "VELIN", "VELLE",
  "VELSK", "VELTE", "VELUM", "VELUR", "VEMOD", "VENDE", "VENNE", "VENTE", "VENØS", "VERDI",
  "VERDT", "VERFT", "VERGE", "VERKE", "VERNE", "VERPE", "VERRE", "VERST", "VERVE", "VESAL",
  "VESEL", "VESEN", "VESIR", "VESKE", "VESLA", "VESLE", "VESTA", "VETTE", "VEVER", "VIDDE",
  "VIDEN", "VIDEO", "VIDJE", "VIFTE", "VIGGE", "VIGIL", "VIGLE", "VIGØR", "VIING", "VIKAR",
  "VIKJE", "VIKKE", "VIKLE", "VIKSK", "VIKTE", "VILJE", "VILLA", "VILLE", "VIMEN", "VIMET",
  "VIMRE", "VIMSE", "VINBY", "VINDE", "VINDU", "VINGA", "VINGE", "VINKE", "VINNE", "VINSJ",
  "VINST", "VINYL", "VINÅR", "VINØS", "VIPPE", "VIPSE", "VIRAK", "VIRAL", "VIRIL", "VIRKE",
  "VIRRE", "VIRUS", "VISER", "VISIR", "VISKE", "VISLE", "VISNE", "VISPE", "VISSE", "VISST",
  "VISTA", "VISUM", "VITAL", "VITEN", "VITJE", "VITNE", "VITRE", "VITSE", "VIVAT", "VODKA",
  "VOFFE", "VOGGE", "VOILE", "VOKAL", "VOKKE", "VOKSE", "VOKTE", "VOLDE", "VOLLE", "VOLOF",
  "VOLTE", "VOLUM", "VOLVE", "VOLVO", "VONOM", "VORDE", "VORTE", "VOTUM", "VOVET", "VRAKE",
  "VRANG", "VREDE", "VRIEN", "VRIER", "VRIKK", "VRIST", "VRÆLE", "VRØVL", "VUGGE", "VULKE",
  "VULST", "VULVA", "VÅGAL", "VÅKEN", "VÅKNE", "VÅNDE", "VÅPEN", "VÅRES", "VÅRYR", "VÅSET",
  "VÅTNE", "VÆPNE", "VÆREN", "VÆSKE", "VÆTER", "VØRDE", "WATER", "WEBBE", "WEBER", "WHIST",
  "WOKKE", "XENIE", "XENON", "XHOSA", "YACHT", "YATZY", "YDMYK", "YLING", "YNDER", "YNDIG",
  "YNGEL", "YNGES", "YNGLE", "YNGRE", "YNGST", "YNKES", "YPPAL", "YPPIG", "YRETE", "YRHET",
  "YRING", "YSTEL", "YSTER", "YTING", "YUCCA", "ZAPPE", "ZLOTY", "ZOOME", "ÅGRER", "ÅKING",
  "ÅLING", "ÅNDER", "ÅPNER", "ÅRBOK", "ÅRBUK", "ÅRDØL", "ÅRENE", "ÅRETE", "ÅRING", "ÅRLIG",
  "ÅRSAK", "ÅRVAK", "ÅRVEG", "ÅRVEI", "ÅSABU", "ÅSDØL", "ÅSETE", "ÅSING", "ÅSKAM", "ÅSSEN",
  "ÅSTAK", "ÅSTED", "ÅTSEL", "ÅTTER", "ÅVERK", "ÆGIDE", "ÆRBAR", "ÆRDUN", "ÆREND", "ÆRING",
  "ÆRLIG", "ØDING", "ØDSEL", "ØDSLE", "ØKING", "ØKSEL", "ØKSLE", "ØLETE", "ØLFAT", "ØLING",
  "ØLOST", "ØLRIK", "ØLRUS", "ØLSBU", "ØLVOM", "ØMHET", "ØNSKE", "ØRENE", "ØRING", "ØRKEN",
  "ØRNEN", "ØRRET", "ØRSKE", "ØRSMÅ", "ØRTEN", "ØRTUG", "ØSING", "ØSKJE", "ØSTPÅ", "ØSTRE",
  "ØVING", "ØVRIG", "ØYDER", "ØYENE", "ØYING", "ØYMÅL", "ØYTUR",
]);

const MAX_GUESSES = 6;
const LEADERBOARD_TIERS = { standard: { label: "Alle" } };
const WORD_LEN = 5;

const KEY_ROWS = [
  ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "Å"],
  ["A", "S", "D", "F", "G", "H", "J", "K", "L", "Æ", "Ø"],
  ["ENTER", "Z", "X", "C", "V", "B", "N", "M", "BACKSPACE"],
];

const STATUS_PRIORITY = { correct: 3, present: 2, absent: 1 };
const STATUS_COLOR = {
  correct: { bg: "rgba(143,201,138,0.28)", border: colors.mint, text: colors.chalkWhite },
  present: { bg: "rgba(232,193,90,0.24)", border: colors.accent, text: colors.chalkWhite },
  absent: { bg: "rgba(237,237,224,0.05)", border: "rgba(237,237,224,0.15)", text: colors.chalkDim },
};

function pickWord(exclude) {
  if (ANSWER_WORDS.length === 1) return ANSWER_WORDS[0];
  let w;
  do {
    w = ANSWER_WORDS[Math.floor(Math.random() * ANSWER_WORDS.length)];
  } while (w === exclude);
  return w;
}

// Standard two-pass Wordle evaluation, correctly handling repeated letters.
function evaluateGuess(guess, target) {
  const result = Array(WORD_LEN).fill("absent");
  const targetArr = target.split("");
  const guessArr = guess.split("");
  const used = Array(WORD_LEN).fill(false);

  for (let i = 0; i < WORD_LEN; i++) {
    if (guessArr[i] === targetArr[i]) {
      result[i] = "correct";
      used[i] = true;
    }
  }
  for (let i = 0; i < WORD_LEN; i++) {
    if (result[i] === "correct") continue;
    const idx = targetArr.findIndex((ch, j) => ch === guessArr[i] && !used[j]);
    if (idx !== -1) {
      result[i] = "present";
      used[idx] = true;
    }
  }
  return result;
}

function Tile({ letter, status, delay, filled }) {
  const style = status
    ? { background: STATUS_COLOR[status].bg, borderColor: STATUS_COLOR[status].border, color: STATUS_COLOR[status].text }
    : {
        background: filled ? "rgba(232,193,90,0.08)" : "rgba(237,237,224,0.02)",
        borderColor: filled ? colors.accent : "rgba(237,237,224,0.3)",
        color: colors.chalkWhite,
      };
  return (
    <div
      className={status ? "rt-reveal" : ""}
      style={{ ...styles.tile, ...style, animationDelay: status ? `${delay}ms` : undefined }}
    >
      {letter}
    </div>
  );
}

export default function Ordjakt() {
  usePageTitle("Ordjakt");
  const [target, setTarget] = useState(() => pickWord(null));
  const [guesses, setGuesses] = useState([]);
  const [currentGuess, setCurrentGuess] = useState("");
  const [status, setStatus] = useState("playing");
  const [message, setMessage] = useState("");
  const [shake, setShake] = useState(false);
  const [gamesPlayed, setGamesPlayed] = useState(1);
  const [shareCopied, setShareCopied] = useState(false);
  const messageTimeout = useRef(null);

  const letterStatus = {}; // best known status per letter, for keyboard coloring
  guesses.forEach((g) => {
    const evalResult = evaluateGuess(g, target);
    g.split("").forEach((ch, i) => {
      const s = evalResult[i];
      if (!letterStatus[ch] || STATUS_PRIORITY[s] > STATUS_PRIORITY[letterStatus[ch]]) {
        letterStatus[ch] = s;
      }
    });
  });

  const flashMessage = (text) => {
    setMessage(text);
    clearTimeout(messageTimeout.current);
    messageTimeout.current = setTimeout(() => setMessage(""), 1600);
  };

  const startNewGame = useCallback(() => {
    setTarget((prev) => pickWord(prev));
    setGuesses([]);
    setCurrentGuess("");
    setStatus("playing");
    setMessage("");
    setGamesPlayed((n) => n + 1);
    setShareCopied(false);
  }, []);

  const shareResult = async () => {
    const emojiMap = { correct: "🟩", present: "🟨", absent: "⬛" };
    const grid = guesses
      .map((g) => evaluateGuess(g, target).map((s) => emojiMap[s]).join(""))
      .join("\n");
    const header = status === "won" ? `Ordjakt ${guesses.length}/${MAX_GUESSES}` : `Ordjakt X/${MAX_GUESSES}`;
    const text = `${header}\n${grid}\nfellesnevner.no/ordjakt`;
    const ok = await copyToClipboard(text);
    if (ok) {
      setShareCopied(true);
      setTimeout(() => setShareCopied(false), 2000);
    }
  };

  const [inputLocked, setInputLocked] = useState(false);

  const handleLetter = useCallback((letter) => {
    if (inputLocked) return;
    setCurrentGuess((prev) => (prev.length < WORD_LEN ? prev + letter : prev));
  }, [inputLocked]);

  const handleBackspace = useCallback(() => {
    if (inputLocked) return;
    setCurrentGuess((prev) => prev.slice(0, -1));
  }, [inputLocked]);

  const handleEnter = useCallback(() => {
    if (status !== "playing" || inputLocked) return;
    if (currentGuess.length < WORD_LEN) {
      setShake(true);
      setTimeout(() => setShake(false), 450);
      flashMessage("For få bokstaver");
      return;
    }
    if (!VALID_GUESSES.has(currentGuess)) {
      setShake(true);
      setTimeout(() => setShake(false), 450);
      flashMessage("Ikke et ord i ordlisten");
      return;
    }
    const nextGuesses = [...guesses, currentGuess];
    setGuesses(nextGuesses);
    setCurrentGuess("");
    // Briefly ignore input right after submitting — absorbs a stray tap
    // that lands on the on-screen keyboard in the same touch gesture as
    // the Enter/Svar press, which would otherwise leak into the next row.
    setInputLocked(true);
    setTimeout(() => setInputLocked(false), 250);
    if (currentGuess === target) {
      setStatus("won");
    } else if (nextGuesses.length >= MAX_GUESSES) {
      setStatus("lost");
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status, currentGuess, guesses, target, inputLocked]);

  useEffect(() => {
    function onKeyDown(e) {
      if (status !== "playing") return;
      if (e.key === "Enter") {
        handleEnter();
        return;
      }
      if (e.key === "Backspace") {
        handleBackspace();
        return;
      }
      if (/^[a-zA-ZæøåÆØÅ]$/.test(e.key)) {
        handleLetter(e.key.toUpperCase());
      }
    }
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [status, handleEnter, handleBackspace, handleLetter]);

  const rows = [];
  for (let i = 0; i < MAX_GUESSES; i++) {
    if (i < guesses.length) {
      const g = guesses[i];
      const evalResult = evaluateGuess(g, target);
      rows.push({ letters: g.split(""), statuses: evalResult });
    } else if (i === guesses.length && status === "playing") {
      const letters = currentGuess.split("").concat(Array(WORD_LEN - currentGuess.length).fill(""));
      rows.push({ letters, statuses: null, current: true });
    } else {
      rows.push({ letters: Array(WORD_LEN).fill(""), statuses: null });
    }
  }

  return (
    <PageShell>
      <div style={shared.header}>
        <Link to="/" style={styles.backLink}>
          ← Fellesnevner
        </Link>
        <h1 style={shared.title}>Ordjakt</h1>
        <p style={shared.subtitle}>Gjett det norske ordet på fem bokstaver — seks forsøk.</p>
      </div>

      <div style={{ textAlign: "center", marginBottom: 10 }}>
        <span style={styles.metaText}>Runde {gamesPlayed} · ingen daglig grense</span>
      </div>

      <div className={shake ? "rt-shake" : ""} style={styles.grid}>
        {rows.map((row, ri) => (
          <div key={ri} style={styles.row}>
            {row.letters.map((letter, ci) => (
              <Tile
                key={ci}
                letter={letter}
                status={row.statuses ? row.statuses[ci] : null}
                delay={ci * 90}
                filled={row.current && letter !== ""}
              />
            ))}
          </div>
        ))}
      </div>

      <div style={styles.messageRow}>{message && <span style={styles.message}>{message}</span>}</div>

      {status !== "playing" && (
        <div style={styles.endBanner}>
          <p style={styles.endText}>
            {status === "won"
              ? `Løst på ${guesses.length} ${guesses.length === 1 ? "forsøk" : "forsøk"}!`
              : `Ordet var ${target}.`}
          </p>
          {status === "won" && <SaveScoreRow game="ordjakt" difficulty="standard" score={guesses.length} />}
          <div style={{ display: "flex", gap: 8, justifyContent: "center", flexWrap: "wrap" }}>
            <button style={{ ...styles.btn, ...styles.btnPrimary }} className="rt-btn" onClick={startNewGame}>
              Nytt ord
            </button>
            <Leaderboard
              game="ordjakt"
              difficulties={LEADERBOARD_TIERS}
              initialDifficulty="standard"
              ascending={true}
              unit=" forsøk"
            />
            <button style={{ ...styles.btn, ...styles.btnGhost }} className="rt-btn" onClick={shareResult}>
              <Share2 size={16} style={{ marginRight: 6 }} /> {shareCopied ? "Kopiert!" : "Del resultat"}
            </button>
          </div>
        </div>
      )}

      {status === "playing" && (
        <div style={styles.keyboard}>
          {KEY_ROWS.map((row, ri) => (
            <div key={ri} style={styles.keyRow}>
              {row.map((key) => {
                if (key === "ENTER") {
                  return (
                    <button key={key} onClick={handleEnter} className="rt-btn" style={{ ...styles.key, ...styles.keyWide }}>
                      SVAR
                    </button>
                  );
                }
                if (key === "BACKSPACE") {
                  return (
                    <button key={key} onClick={handleBackspace} className="rt-btn" style={{ ...styles.key, ...styles.keyWide }}>
                      <Delete size={18} />
                    </button>
                  );
                }
                const s = letterStatus[key];
                return (
                  <button
                    key={key}
                    onClick={() => handleLetter(key)}
                    className="rt-btn"
                    style={{
                      ...styles.key,
                      background: s ? STATUS_COLOR[s].bg : "rgba(237,237,224,0.05)",
                      borderColor: s ? STATUS_COLOR[s].border : "rgba(237,237,224,0.3)",
                      color: s ? STATUS_COLOR[s].text : colors.chalkWhite,
                    }}
                  >
                    {key}
                  </button>
                );
              })}
            </div>
          ))}
        </div>
      )}
    </PageShell>
  );
}

const styles = {
  backLink: {
    display: "inline-block",
    color: "#8FA089",
    fontSize: 12.5,
    fontFamily: "'IBM Plex Sans', sans-serif",
    textDecoration: "none",
    marginBottom: 10,
  },
  metaText: { color: "#8FA089", fontSize: 12, fontFamily: "'IBM Plex Mono', monospace" },
  grid: { display: "flex", flexDirection: "column", gap: 8, alignItems: "center", marginBottom: 8 },
  row: { display: "flex", gap: 8 },
  tile: {
    width: "clamp(42px, 11vw, 56px)",
    height: "clamp(42px, 11vw, 56px)",
    border: "2px solid",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(18px, 5vw, 24px)",
    fontWeight: 700,
    fontFamily: "'IBM Plex Sans', sans-serif",
    textTransform: "uppercase",
    transition: "background 0.15s, border-color 0.15s",
  },
  messageRow: { minHeight: 24, textAlign: "center", marginTop: 4, marginBottom: 4 },
  message: { color: "#E8C15A", fontSize: 13, fontWeight: 500 },
  endBanner: { textAlign: "center", marginTop: 10, marginBottom: 16 },
  endText: { color: "#EDEDE0", fontSize: 14, marginBottom: 10, fontFamily: "'IBM Plex Sans', sans-serif" },
  btn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 8,
    padding: "12px 20px",
    fontSize: 13.5,
    fontWeight: 600,
    fontFamily: "'IBM Plex Sans', sans-serif",
    minHeight: 44,
    cursor: "pointer",
  },
  btnPrimary: { background: "#E8C15A", color: "#16221A" },
  btnGhost: { background: "transparent", border: "1.5px dashed rgba(237,237,224,0.4)", color: "#EDEDE0" },
  keyboard: { display: "flex", flexDirection: "column", gap: 6, marginTop: 14, alignItems: "center" },
  keyRow: { display: "flex", gap: 5, justifyContent: "center" },
  key: {
    border: "1.5px solid",
    borderRadius: 6,
    minWidth: 30,
    height: 44,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "'IBM Plex Sans', sans-serif",
    cursor: "pointer",
    padding: "0 8px",
    WebkitTapHighlightColor: "transparent",
  },
  keyWide: { minWidth: 52, fontSize: 11, padding: "0 6px" },
};
