// A broad, hand-checked list of country/capital pairs, in Norwegian.
// "common" marks larger, more widely known countries (used for "Lett"
// difficulty modes across games). A handful of countries have genuinely
// disputed or multi-capital arrangements (Bolivia, South Africa,
// Israel/Palestine, Kosovo, Taiwan) — the list uses the answer most
// commonly taught in general geography contexts, not a political
// statement.
export const COUNTRIES = [
  { country: "Norge", capital: "Oslo", common: true },
  { country: "Sverige", capital: "Stockholm", common: true },
  { country: "Danmark", capital: "København", common: true },
  { country: "Finland", capital: "Helsingfors", common: true },
  { country: "Island", capital: "Reykjavik", common: true },
  { country: "Storbritannia", capital: "London", common: true },
  { country: "Irland", capital: "Dublin", common: true },
  { country: "Frankrike", capital: "Paris", common: true },
  { country: "Tyskland", capital: "Berlin", common: true },
  { country: "Nederland", capital: "Amsterdam", common: true },
  { country: "Belgia", capital: "Brussel", common: true },
  { country: "Luxembourg", capital: "Luxembourg", common: false },
  { country: "Sveits", capital: "Bern", common: true },
  { country: "Østerrike", capital: "Wien", common: true },
  { country: "Spania", capital: "Madrid", common: true },
  { country: "Portugal", capital: "Lisboa", common: true },
  { country: "Italia", capital: "Roma", common: true },
  { country: "Hellas", capital: "Athen", common: true },
  { country: "Polen", capital: "Warszawa", common: true },
  { country: "Tsjekkia", capital: "Praha", common: true },
  { country: "Slovakia", capital: "Bratislava", common: false },
  { country: "Ungarn", capital: "Budapest", common: true },
  { country: "Romania", capital: "Bucuresti", common: true },
  { country: "Bulgaria", capital: "Sofia", common: false },
  { country: "Kroatia", capital: "Zagreb", common: true },
  { country: "Slovenia", capital: "Ljubljana", common: false },
  { country: "Serbia", capital: "Beograd", common: true },
  { country: "Bosnia-Hercegovina", capital: "Sarajevo", common: false },
  { country: "Montenegro", capital: "Podgorica", common: false },
  { country: "Nord-Makedonia", capital: "Skopje", common: false },
  { country: "Albania", capital: "Tirana", common: false },
  { country: "Kosovo", capital: "Pristina", common: false },
  { country: "Estland", capital: "Tallinn", common: true },
  { country: "Latvia", capital: "Riga", common: true },
  { country: "Litauen", capital: "Vilnius", common: true },
  { country: "Ukraina", capital: "Kyiv", common: true },
  { country: "Hviterussland", capital: "Minsk", common: false },
  { country: "Moldova", capital: "Chisinau", common: false },
  { country: "Russland", capital: "Moskva", common: true },
  { country: "Malta", capital: "Valletta", common: false },
  { country: "Kypros", capital: "Nikosia", common: false },
  { country: "Monaco", capital: "Monaco", common: false },
  { country: "San Marino", capital: "San Marino", common: false },
  { country: "Andorra", capital: "Andorra la Vella", common: false },
  { country: "Liechtenstein", capital: "Vaduz", common: false },
  { country: "Kina", capital: "Beijing", common: true },
  { country: "Japan", capital: "Tokyo", common: true },
  { country: "Sør-Korea", capital: "Seoul", common: true },
  { country: "Nord-Korea", capital: "Pyongyang", common: true },
  { country: "Taiwan", capital: "Taipei", common: false },
  { country: "India", capital: "New Delhi", common: true },
  { country: "Pakistan", capital: "Islamabad", common: true },
  { country: "Bangladesh", capital: "Dhaka", common: false },
  { country: "Sri Lanka", capital: "Colombo", common: false },
  { country: "Nepal", capital: "Kathmandu", common: false },
  { country: "Bhutan", capital: "Thimphu", common: false },
  { country: "Myanmar", capital: "Naypyidaw", common: false },
  { country: "Thailand", capital: "Bangkok", common: true },
  { country: "Vietnam", capital: "Hanoi", common: true },
  { country: "Laos", capital: "Vientiane", common: false },
  { country: "Kambodsja", capital: "Phnom Penh", common: false },
  { country: "Malaysia", capital: "Kuala Lumpur", common: true },
  { country: "Singapore", capital: "Singapore", common: true },
  { country: "Indonesia", capital: "Jakarta", common: true },
  { country: "Filippinene", capital: "Manila", common: true },
  { country: "Brunei", capital: "Bandar Seri Begawan", common: false },
  { country: "Øst-Timor", capital: "Dili", common: false },
  { country: "Mongolia", capital: "Ulaanbaatar", common: false },
  { country: "Kasakhstan", capital: "Astana", common: false },
  { country: "Usbekistan", capital: "Tasjkent", common: false },
  { country: "Turkmenistan", capital: "Asjkhabad", common: false },
  { country: "Kirgisistan", capital: "Bisjkek", common: false },
  { country: "Tadsjikistan", capital: "Dusjanbe", common: false },
  { country: "Afghanistan", capital: "Kabul", common: true },
  { country: "Iran", capital: "Teheran", common: true },
  { country: "Irak", capital: "Bagdad", common: true },
  { country: "Syria", capital: "Damaskus", common: true },
  { country: "Libanon", capital: "Beirut", common: false },
  { country: "Jordan", capital: "Amman", common: false },
  { country: "Israel", capital: "Jerusalem", common: true },
  { country: "Palestina", capital: "Ramallah", common: false },
  { country: "Saudi-Arabia", capital: "Riyadh", common: true },
  { country: "Yemen", capital: "Sanaa", common: false },
  { country: "Oman", capital: "Muskat", common: false },
  { country: "De forente arabiske emirater", capital: "Abu Dhabi", common: true },
  { country: "Qatar", capital: "Doha", common: false },
  { country: "Bahrain", capital: "Manama", common: false },
  { country: "Kuwait", capital: "Kuwait", common: false },
  { country: "Tyrkia", capital: "Ankara", common: true },
  { country: "Georgia", capital: "Tbilisi", common: false },
  { country: "Armenia", capital: "Jerevan", common: false },
  { country: "Aserbajdsjan", capital: "Baku", common: false },
  { country: "Egypt", capital: "Kairo", common: true },
  { country: "Libya", capital: "Tripoli", common: false },
  { country: "Tunisia", capital: "Tunis", common: false },
  { country: "Algerie", capital: "Alger", common: false },
  { country: "Marokko", capital: "Rabat", common: true },
  { country: "Mauritania", capital: "Nouakchott", common: false },
  { country: "Mali", capital: "Bamako", common: false },
  { country: "Niger", capital: "Niamey", common: false },
  { country: "Tsjad", capital: "N'Djamena", common: false },
  { country: "Sudan", capital: "Khartoum", common: false },
  { country: "Sør-Sudan", capital: "Juba", common: false },
  { country: "Etiopia", capital: "Addis Abeba", common: true },
  { country: "Eritrea", capital: "Asmara", common: false },
  { country: "Djibouti", capital: "Djibouti", common: false },
  { country: "Somalia", capital: "Mogadishu", common: false },
  { country: "Kenya", capital: "Nairobi", common: true },
  { country: "Uganda", capital: "Kampala", common: false },
  { country: "Tanzania", capital: "Dodoma", common: false },
  { country: "Rwanda", capital: "Kigali", common: false },
  { country: "Burundi", capital: "Gitega", common: false },
  { country: "Den demokratiske republikken Kongo", capital: "Kinshasa", common: false },
  { country: "Republikken Kongo", capital: "Brazzaville", common: false },
  { country: "Den sentralafrikanske republikk", capital: "Bangui", common: false },
  { country: "Kamerun", capital: "Yaoundé", common: false },
  { country: "Nigeria", capital: "Abuja", common: true },
  { country: "Benin", capital: "Porto-Novo", common: false },
  { country: "Togo", capital: "Lomé", common: false },
  { country: "Ghana", capital: "Accra", common: true },
  { country: "Elfenbenskysten", capital: "Yamoussoukro", common: false },
  { country: "Liberia", capital: "Monrovia", common: false },
  { country: "Sierra Leone", capital: "Freetown", common: false },
  { country: "Guinea", capital: "Conakry", common: false },
  { country: "Guinea-Bissau", capital: "Bissau", common: false },
  { country: "Senegal", capital: "Dakar", common: false },
  { country: "Gambia", capital: "Banjul", common: false },
  { country: "Burkina Faso", capital: "Ouagadougou", common: false },
  { country: "Kapp Verde", capital: "Praia", common: false },
  { country: "Angola", capital: "Luanda", common: false },
  { country: "Zambia", capital: "Lusaka", common: false },
  { country: "Zimbabwe", capital: "Harare", common: false },
  { country: "Mosambik", capital: "Maputo", common: false },
  { country: "Malawi", capital: "Lilongwe", common: false },
  { country: "Namibia", capital: "Windhoek", common: false },
  { country: "Botswana", capital: "Gaborone", common: false },
  { country: "Sør-Afrika", capital: "Pretoria", common: true },
  { country: "Eswatini", capital: "Mbabane", common: false },
  { country: "Lesotho", capital: "Maseru", common: false },
  { country: "Madagaskar", capital: "Antananarivo", common: false },
  { country: "Mauritius", capital: "Port Louis", common: false },
  { country: "Komorene", capital: "Moroni", common: false },
  { country: "Seychellene", capital: "Victoria", common: false },
  { country: "Sao Tome og Principe", capital: "São Tomé", common: false },
  { country: "Gabon", capital: "Libreville", common: false },
  { country: "Ekvatorial-Guinea", capital: "Malabo", common: false },
  { country: "USA", capital: "Washington D.C.", common: true },
  { country: "Canada", capital: "Ottawa", common: true },
  { country: "Mexico", capital: "Mexico by", common: true },
  { country: "Guatemala", capital: "Guatemala by", common: false },
  { country: "Belize", capital: "Belmopan", common: false },
  { country: "Honduras", capital: "Tegucigalpa", common: false },
  { country: "El Salvador", capital: "San Salvador", common: false },
  { country: "Nicaragua", capital: "Managua", common: false },
  { country: "Costa Rica", capital: "San José", common: false },
  { country: "Panama", capital: "Panama by", common: false },
  { country: "Cuba", capital: "Havana", common: true },
  { country: "Jamaica", capital: "Kingston", common: false },
  { country: "Haiti", capital: "Port-au-Prince", common: false },
  { country: "Den dominikanske republikk", capital: "Santo Domingo", common: false },
  { country: "Bahamas", capital: "Nassau", common: false },
  { country: "Trinidad og Tobago", capital: "Port of Spain", common: false },
  { country: "Barbados", capital: "Bridgetown", common: false },
  { country: "Colombia", capital: "Bogotá", common: true },
  { country: "Venezuela", capital: "Caracas", common: true },
  { country: "Guyana", capital: "Georgetown", common: false },
  { country: "Surinam", capital: "Paramaribo", common: false },
  { country: "Ecuador", capital: "Quito", common: false },
  { country: "Peru", capital: "Lima", common: true },
  { country: "Bolivia", capital: "Sucre", common: false },
  { country: "Chile", capital: "Santiago", common: true },
  { country: "Argentina", capital: "Buenos Aires", common: true },
  { country: "Paraguay", capital: "Asunción", common: false },
  { country: "Uruguay", capital: "Montevideo", common: false },
  { country: "Brasil", capital: "Brasília", common: true },
  { country: "Australia", capital: "Canberra", common: true },
  { country: "New Zealand", capital: "Wellington", common: true },
  { country: "Papua Ny-Guinea", capital: "Port Moresby", common: false },
  { country: "Fiji", capital: "Suva", common: false },
  { country: "Salomonøyene", capital: "Honiara", common: false },
  { country: "Vanuatu", capital: "Port Vila", common: false },
  { country: "Samoa", capital: "Apia", common: false },
  { country: "Tonga", capital: "Nuku'alofa", common: false },
  { country: "Kiribati", capital: "Tarawa", common: false },
  { country: "Palau", capital: "Ngerulmud", common: false },
  { country: "Marshalløyene", capital: "Majuro", common: false },
  { country: "Mikronesiaføderasjonen", capital: "Palikir", common: false },
  { country: "Nauru", capital: "Yaren", common: false },
  { country: "Tuvalu", capital: "Funafuti", common: false },
];
